### PR TITLE
Fix for CreateFileMapping 

### PR DESCRIPTION
**Pull request by sefai**
Save file size to later know if MmCanFileBeTruncated call is needed or not.

### CODE REVIEW

**Comment by Rondom** [comment]
Can we run runkarr on this PR to see if it improves things compared to the current implementation?
See #519 for a link to a branch that has an installation script for the MS filesystem testing utilities.

**Comment by Rondom** [comment]
https://github.com/Rondom/dokany/tree/ifstest/scripts

**Comment by sefai** [comment]
Hello @Rondom 
Do you want me to install MS filesystem testing utilities locally and execute the tests? Isn't it possible to run that IFSTest on Appveyor?

**Comment by Rondom** [comment]
I will do it at a later point. I only thought that a this can be helpful that everything is all right, but I just noticed that it requires additional work. I will add it to AppVeyor at a later point.

**Comment by Liryna** [comment]
Hi @sefai ,

Thanks a lot for the PR !
All seems to be correct but could you just add some fcb lock when accessing the FileSize ?
This should not create deadlock but worst to retry with it 👍

**Comment by sefai** [comment]
Hello @Liryna 

I have tried locking FCB when accessing the FileSize, but unfortunately it creates a deadlock.

Also, my PR is not correct, the if clause should be negated 

`if (!(irp->Flags & IRP_PAGING_IO)) `

Can you do that, or should I create a new PR?

**Comment by Liryna** [comment]
@sefai I have add a lock to the filesize set value and rebase your commit
https://github.com/dokan-dev/dokany/commit/38348f5fe160e9f2d384b992c69eed8b8d8e1824

Thank again for your time and sorry for the delay !

**Pull request closed without merging**
