### PR TITLE
Fix current session issues

### PR DESCRIPTION
**Pull request by marinkobabic**
The following issues should be fixed

https://github.com/dokan-dev/dokany/issues/517
https://github.com/dokan-dev/dokany/issues/332

and the following one may also work properly for session drives
https://github.com/dokan-dev/dokany/issues/312

### CODE REVIEW

**Comment by Rondom** [comment]
Did you intentionally close this one?

**Comment by marinkobabic** [comment]
Yes. I have created a new one.

Am 30.05.2017 23:10 schrieb "Andreas Gnau" <notifications@github.com>:

**Comment by Liryna** [comment]
Hi @marinkobabic ,

Sorry for the delay, I took a look at the PR, this seems to be good !
I will just take a little more time to test to the issue related to it and see if it can also be closed.

Thank again for your work ! ❤️

**Comment by Liryna** [comment]
Hi @marinkobabic ,

I tried to reproduce all the issues:
https://github.com/dokan-dev/dokany/issues/517 : I could not test this case exactly but it should work 👍 
https://github.com/dokan-dev/dokany/issues/332 : Yes it works! the drive letter can be reused ! The only strange behavior is that the device is still in the explorer and can be access but empty after killing the mirror.
https://github.com/dokan-dev/dokany/issues/312 : User A can dismount user B drive. Maybe here we should detect in the kernel if the request comes from an admin or simple user and give only rights to admin to dismount all devices.

**Comment by marinkobabic** [comment]
User A should not be able to unmount the drive of the user B if both use
the current session option. The will have different windows sessions.

Am 05.06.2017 13:42 schrieb "Liryna" <notifications@github.com>:

**Comment by shashiu** [comment]
Is there going to be a new build with this fix ?

**Comment by Liryna** [comment]
@shashiu There is every time a snapshot build made by the CI selfsigned
https://ci.appveyor.com/api/buildjobs/ss79dhy6ah90bfqj/artifacts/DokanSetup-1.0.3.1193.exe

https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot

It would be nice if you could see if this fix your issue before making a fix release official (that take some times).

**Comment by shashiu** [comment]
@Liryna<mailto:notifications@github.com>, I checked out the build and it seems to fix the issue with remote desktop sessions, that I was seeing before. I'll keep testing it and let you know if I find any new issues.


Thanks.


________________________________

**Comment by Liryna** [comment]
Hi @marinkobabic ,

Sorry for the long delay 😢 I merged this only now.
Thanks a lot again for your work !

**Pull request merged**
