### PR TITLE
fix bsod issue related to filesystem mount on Windows 10 build 14936

### PR DESCRIPTION
**Pull request by marinkobabic**
Fix for issue https://github.com/dokan-dev/dokany/issues/359. Please do a review if I'm doing the buffer copy correct. Maybe is there a much simpler way to compare the strings?

The issue is related to the dokan architecture. If we face more such problems in the future a generic approach must be implement to avoid such problems.

### CODE REVIEW

**Comment by Liryna** [comment]
Hi @marinkobabic ,

Well found as always and extremely appreciate ❤️ !

About unicode string compare, can we not just call RtlCompareUnicodeString with fileObject->FileName and systemVolume, check the return value like:

```
RtlInitUnicodeString(&systemVolume, L"\\System Volume Information");
if (RtlCompareUnicodeString(&systemVolume, &(fileObject->FileName), TRUE) < 0) {
   DDbgPrint("  It's an access to System Volume, so don't return SUCCESS. We don't have one.")
   status = STATUS_NO_SUCH_FILE;
   __leave;
}
```
it would avoid the buffer copy.

RtlCompareUnicodeString doc says that `< Zero : String1 is less than String2.`, so it "should" be alright 😄 do you think you can test something like that ?

**Comment by marinkobabic** [comment]
What we need is the check if the path starts with \System Volume Information

The passed in path is 
\System Volume Information\Cloud Files\

**Comment by Liryna** [comment]
Yes, I tought `RtlCompareUnicodeString` would return a <= 0 value if `fileObject->FileName` started with `\System Volume Information`.
I tested it and I was wrong 😢 

```
    UNICODE_STRING string1, string2, string3, string4;
    RtlInitUnicodeString(&string1, L"\\System Volume Information");
    RtlInitUnicodeString(&string2, L"\\System Volume Information\\Cloud Files\\");
    LONG result = RtlCompareUnicodeString(&string1, &string2, TRUE);
    DDbgPrint("RtlCompareUnicodeString 1 result %ld\n", result);

    RtlInitUnicodeString(&string3, L"\\System Volume Information2\\Cloud Files\\");
    result = RtlCompareUnicodeString(&string1, &string3, TRUE);
    DDbgPrint("RtlCompareUnicodeString 2 result %ld\n", result);

    RtlInitUnicodeString(&string3, L"\\test");
    result = RtlCompareUnicodeString(&string1, &string4, TRUE);
    DDbgPrint("RtlCompareUnicodeString 3 result %ld\n", result);


.....

[DokanFS] RtlCompareUnicodeString 1 result -13
[DokanFS] RtlCompareUnicodeString 2 result -14
[DokanFS] RtlCompareUnicodeString 3 result 26
```

BUT this worked:

```
    UNICODE_STRING systemVolume;
    RtlInitUnicodeString(&systemVolume, L"\\System Volume Information");

    if (systemVolume.Length >= fileObject->FileName.Length)
    {
      LPCWSTR p1, p2;
      p1 = systemVolume.Buffer;
      p2 = fileObject->FileName.Buffer;
      unsigned int len = 0;
      LONG ret = 0;
      while (!ret && len < 26) {
          ret = *p1++ - *p2++;
          ++len;
      }
      if (ret == 0 && (systemVolume.Length == fileObject->FileName.Length || *p2 == L'\\'))  {
        DDbgPrint("  It's an access to System Volume, so don't return SUCCESS. We don't have one.")
          status = STATUS_NO_SUCH_FILE;
        __leave;
      }
    }
```
it is not much but...we avoid allocating memory 😃 

Could you try it on your side if still work and update your PR ❤️ ?

**Comment by marinkobabic** [comment]
@Liryna 
Have done the requested changes and it works fine 👍 Nice solution to avoid memory allocation 😄 
So let's hope how that the BSOD can't be reproduced anymore. Thanks a lot!

**Comment by Liryna** [comment]
Thank you for the quick changes ❤️ !

**Pull request merged**
