### PR TITLE
fix read file exception

### PR DESCRIPTION
**Pull request by hefengliang**
Fixes # .
When reading data with a large delay, the IRP times out, which will cause the file object to be accidentally released.
When reading data in multiple reads, due to the dependency on the file object (hndl-> get_name ()), uncontrollable pointer errors will result.
This question has also been asked before: https://github.com/dokan-dev/dokany/issues/734

I fixed this problem, and through actual testing, I found that there would be no more file reading problems, but I do n’t know if the data returned by read can still be received by the kernel and processed correctly when the file object is released. At least my application looks normal.

### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the existing documentation
- [x] My changes generate no new warnings
- [ ] I have updated the change log (Add/Change/Fix)
- [ ] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

-Compare the code, only two lines of code changed
-
-

### CODE REVIEW

**Comment by hefengliang** [comment]
This is the state when the exception occurred：
image

**Comment by Liryna** [comment]
Hi @hefengliang ,

I see your situation, you are getting a read / write after the object was released. This fix just avoid the crash but do not fix the behavior.
You can get a read / write after the cleanup but not after the close. Can you track when the name is released in your case ?

**Comment by hefengliang** [comment]
In my application, this problem only occurs in the case of a poor network. Due to the complicated environment, please forgive me for not being able to write a demo. I exported an abnormal dmp file. Is it useful to you?
dmp is based on Dokan Library-1.3.1 \ x86.
Since there is a 10M limit here, I sent the dmp file to your email address：liryna.stark@gmail.com

**Comment by Liryna** [comment]
Sorry for the delay @hefengliang Could you please rebase the commit into one for me to merge ?

**Comment by hefengliang** [comment]
I use svn to develop, GIT is not commonly used, I merge as I understand

**Comment by hefengliang** [comment]
@Liryna   I use svn to develop, GIT is not commonly used, I merge as I understand

**Comment by Liryna** [comment]
Thank you @hefengliang for your contribution ! :+1:

**Pull request merged**
