### PR TITLE
fix mounting issue

### PR DESCRIPTION
**Pull request by marinkobabic**
This should solve the remaining mounting issue and the redirector

### CODE REVIEW

**Comment by Liryna** [comment]
Hey @marinkobabic 

This work perfectly ! :relaxed: 

Your last contributions have really improved alot dokan and fixed the main issues ! :heart:

I will try to make a beta2 tomorrow with the new installer since the 1.0.0 have reached all milestones.

**Comment by Maxhy** [comment]
I'm going to love this release, it will fix so many things excepted since years!

Thank you again @marinkobabic, I would have done the same for this network mount issue fix :smile:, good work.
Interesting things about boot sector you made here, I'm just not 100% sure about your File System Recognizer read request check here, wouldn't `if (fileObject == NULL && Irp->MdlAddress != NULL) {` match other cases?

**Comment by marinkobabic** [comment]
It may be. We could also do a check how many bytes they are going to read. NTFS reads for example just the first 512 bytes. If we face some problems we can investigate.

Actually the Windows 8.1 default pdf viewer can't open pdf files. Oplock implementation seems to not be complete. 

If we once decide to support pnp this should be done in a separate bus driver.

The redirector implementation changed since Vista. Actual implementation feels like a hack just  to have a network drive. Redirector should be implemented in a separate dll. The drive should be a normal drive with redirector support. 

There are many things  to do :smiley:

**Comment by Liryna** [comment]
@marinkobabic I agree with you there is a lot to do !
But we can already be proud for having reborn Dokan project and bring him at this level of device implementation !

As you seen, I have create different issues related to your todo list :smiley:
About pnp and redirector, could you create issues with somes informations ? (I don't really know what to do)
This would give opportunities to contributors to help us.

**Comment by marinkobabic** [comment]
I totally agree and in generally I think you and Maxhy are doing a great job. Without you two, we wouldn't have dokan anymore. Thank you!

Let's go on :smile:

**Pull request merged**
