### PR TITLE
Description:Fix up dokanfuse mount error when chinese mount path.

### PR DESCRIPTION
**Pull request by FaerieLee**
Fixes # .issue 893 Fix up dokanfuse mount error when chinese mount path.

### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the existing documentation
- [ ] My changes generate no new warnings
- [ ] I have updated the change log (Add/Change/Fix)
- [ ] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by Liryna** [comment]
Thank you @FaerieLee for the PR.
Why not directly using `utf8_to_wchar_buf` instead of `utf8_to_unicode` ? It was not working ?

**Comment by FaerieLee** [comment]
No, I did not try to use utf8_to_wchar_buf, because it's very low probability that our file system would crash in other scenarios when running in the function , but I couldn't find the reason. So if the mount path of user occasionally trigger the crash, it's a bad experience. So I use  utf8_to_unicode instead of utf8_to_wchar_buf. Thank you for your comment.

**Comment by FaerieLee** [comment]
I reproduce the failure. I find that it's our concurrent problem which result to  utf8_to_wchar_buf crash. I think that utf8_to_wchar_buf can fix up chinese mount path problem, but I need to try to validate

**Comment by FaerieLee** [comment]
I have a question. How can I know the result of calling utf8_to_wchar_buf  ? If utf8_to_wchar_buf  encounts some unexpected exceptions. I don't realize it, And if the funtion which calling utf8_to_wchar_buf  cotinues, the result would be unexpected.

**Comment by Liryna** [comment]
No unfortunately `utf8_to_wchar_buf` do not return any error even if it could since it calls `convert_char` that does return -1 on failure. if you are interested to change the prototype, you can 👍

**Comment by FaerieLee** [comment]
I fix up this question by using  utf8_to_wchar_buf, Please review.

**Comment by Liryna** [comment]
`convert_char` return -1 in failure but you made `utf8_to_wchar_buf` return 0 in case of failure 
https://github.com/dokan-dev/dokany/blob/08502afa1de0b32d8a59d090bfa73ecdd12374ab/dokan_fuse/src/utils.cpp#L144
they should both have the same type of failure otherwise your check would not work

**Comment by FaerieLee** [comment]
The return type of conver_char is size_t, which is unsigned type. Although it return -1,  I determine nothing by this value, because it's always greater or equals than 0. So I made utf8_to_wchar_buf  return 0 in case of failure.

**Comment by Liryna** [comment]
What happen with you condition == 0 of convert return - 1?

**Comment by FaerieLee** [comment]
I didn't understand your idea until now. your idea is that conver_char return - 1, although return value is converted into a unsigned value, I can check failue by this very large unsigned number. If so, I think that utf8_to_wchar_buf should return -1.

**Comment by FaerieLee** [comment]
fix up utf8_to_wchar_buf return -1. please review

**Comment by Liryna** [comment]
Thank you @FaerieLee for the change. The CI has reported different warning during the build
https://ci.appveyor.com/project/Maxhy/dokany/builds/33432130/job/iareml00ux4bp0ee#L2287
Could you take a look at it ?

**Comment by FaerieLee** [comment]
OK, I have fixed up the warning. Please review it.

**Comment by Liryna** [comment]
Thanks for the quick changes and for your contribution! @FaerieLee very appreciated

**Pull request merged**
