### PR TITLE
Installer: Make sure that all updates are installed on Win7

### PR DESCRIPTION
**Pull request by Rondom**
On Windows 7 and 2008 R2 the installer did not check whether SP1 and KB3033929 are installed which led to confused users like me or #187 or #244. For details see the individual commits.

I will need to do some testing, to test the different combinations. ETA end of this week!

### CODE REVIEW

**Comment by Liryna** [comment]
:+1: Tell me when I can test it !

**Comment by Rondom** [comment]
@Liryna You can test as soon and as much as you want :-) It works on my patched Win 2008 R2. 

What should be tested (probably in that order):
* without .NET4 (bundle)
* with .NET but without SP1 (both MSI and bundle)
* with .NET and SP1 but without KB3033929 (both MSI and bundle)
* with .NET, SP1 and KB3033929 (both MSI and bundle)

I do not really feel like testing both 32 and 64 bit.

**Comment by Liryna** [comment]
Worked for me :+1: 

Thank you @Rondom for your contributions as always :heart: !!!

Well found for `Wintrust.dll`  check :D

**Comment by Rondom** [comment]
Did some tests and it does not work correctly.  Here is why:

> **Important:** When doing a locale-neutral search for a file, **you must set the MinVersion property to one revision number lower than the actual version you want to search for.** In this example, while we want to find file version 6.0.6001.1751, the MinVersion is set to 6.0.6001.1750. This is because of a quirk in how the Windows Installer matches file versions. More information is available in the Windows Installer documentation.

I have no words for this...

**Comment by Liryna** [comment]
Oh :cry: 
Do we need to reduce the MinVersion so ?

**Comment by Rondom** [comment]
Probably... I really wonder why WiX does not abstract this oddity away...
Also I am seriously interested why it has to be *lower* and not *higher* by one...

Here are my results so far. Tested with DokanSetup-1.0.0.3616.exe (Git bbbdbcb8)

    +----------+-------+-----+-----------+-----------------+---------------+
    |OS        | .NET4 | SP1 | KB3033929 | Bundle-Msg      | MSI-Msg       |
    |----------+-------+-----+-----------+-----------------+---------------|
    | Win7 x86 |   o   |  o  |    o      | No SP1          | No .NET4      |
    | Win7 x86 |   x   |  o  |    o      | No SP1          | No SP1        |
    | Win7 x86 |   x   |  x  |    o      | No KB3033929 ¹  | No KB3033929  |
    | Win7 x86 |   o   |  x  |    o      | No KB3033929 ¹  | No .NET 4.0   |
    | Win7 x86 |   x   |  x  |   (x)²    | No KB3033929 ¹  | No KB3033929  |
    | Win7 x86 |   x   |  x  |    x      |                 |               |
    +----------+-------+-----+-----------+-----------------+---------------+

    ¹ installs bundled software (.NET 4.0 and runtimes) before failing with missing KB3033929
    ² No reboot

None of the error-messages are wrong, but not everything is optimal and one could make the user experience nicer by giving more informative messages by reordering the checks and/or by adding a check for KB3033929 to the bundle (see footnote). I honestly lack the motivation and time for this.  My main goal was that the installer or Dokan does not fail in mysterious ways
As @js69 very nicely put it, supporting such configurations is a valiant but somewhat quixotic effort. **So if someone is valiant and wants to improve the user experience and do the required testing (see above), please go ahead ;-)**

**What I will do is fix the KB3033929-check by submitting a PR and test on Monday or Tuesday.**

**Pull request merged**
