### PR TITLE
Add NET 4.0 in bundle, add check in MSI and RebootPending check

### PR DESCRIPTION
**Pull request by js69**
Add NET 4.0 package in bundle and check in MSI and check for
RebootPending

Rebased on current master, was missing netfx extension.

### CODE REVIEW

**Comment by Rondom** [comment]
You do not need to close and open a new pull-request for each fix you do to your pull-request.
Simply rebase your local branch and force-push (git push --force) and the pull request will be updated with your updates. The old history will even be preserved by GitHub for reference.

**Comment by js69** [comment]
I'm just avoiding the console as much as possible. What would have been the correct rebase method?

**Comment by Rondom** [comment]
Well, your tree looks clean, so you DID rebase correctly and the branch-name you force-pushed to is also the same for each of the pull-requests. I do not know what you did with the actual pull-requests. Pull-requests are a GitHub proprietary thing. How you you create and close the pull-requests?
https://github.com/dokan-dev/dokany/pulls?utf8=%E2%9C%93&q=is%3Apr+%22Add+NET+4.0+in+bundle%22

I don't know what kind of GUIs there are and which you are using and I am mostly a command-line/Linux guy, so I cannot help you much. I can only describe how my workflow looks like. There are many workflows and I do not consider mine the only correct way to do it.

Prerequisite: Have two remotes configured (the dokan-dev and my own "rondom" remote).

0. Notice some bug or feature I want to implement
1. Make sure master is the same as dokan-dev/master (git pull + ensure that I do not have any unmerged commits in my local master-branch)
2. Create new branch myfeaturebug, commit changes
3. Rebase against latest dokan-dev/master if necessary
4. Push this branch to Rondom/myfeaturebug
5. Submit pull-request using the GitHub-Web UI
6. Do further changes in case they are required
7. Push those changes. If I have rebased (i.e. rewrote history), the push will fail, because I would overwrite the changes that are in my remote-branch. In this case I will do the force-push and overwrite the old changes in my remote-branch. As far as I know GitHub will still preserve the old commits in the pull requests in case anyone is interested in those.
8. Changes show up in the existing pull request.

**Comment by Liryna** [comment]
Hi @js69 ,

Thank you for your contribution as always, very appreciate ! :heart: 

This seems to work on my side :smiley:

**Pull request merged**
