### PR TITLE
sys: Add IsUnmounting to the DCB

### PR DESCRIPTION
**Pull request by taruti**
As suggested by @marinkobabic on https://github.com/dokan-dev/dokany/issues/272

I can get this to hit occasionally in stress tests. 

However this does not replace https://github.com/dokan-dev/dokany/pull/280

### CODE REVIEW

**Comment by Liryna** [comment]
Hi @taruti ,

Thank you for your contribution ! :+1: 

Does this improve one of the issue you are facing ?

**Comment by marinkobabic** [comment]
I will do some small improvements and see if you still can reproduce your issue. Just wait for a new pull request.

**Comment by taruti** [comment]
@Liryna With both this and #280 (CCB is NULL) I am seeing less crashes with the stress test in #230.

#280 seems to be encountered more frequently than this, but this is also encountered sometimes.

**Comment by marinkobabic** [comment]
@taruti 
Please can you check if this solves the ccb null problem https://github.com/marinkobabic/dokany/tree/FixNullIReference If we do not understand why is ccb null, we will not be able to fix the issue definitely. But with your help we should be able to identify the source of the problem.

**Comment by taruti** [comment]
With https://github.com/marinkobabic/dokany/tree/FixNullIReference I get a fast crash without good logs.

Tested with example code from #230 and Windows 7.

**Comment by marinkobabic** [comment]
If you put your fix with ccb into FixNullReference code, then you don't have the crash?

**Comment by taruti** [comment]
Still have a crash. I think your patch introduces a new crash. Also with two flags for Mounted/IsUnmounted most of the code checks only one of them.

Does that branch work for you with the example code from #230 on Windows 7?

**Comment by marinkobabic** [comment]
This items can be null, which is fine:

- ccb
- FsContext2

So the question which of this items is null in your case, when you get the crash:

- IrpEntry->FileObject
- vcb
- vcb->Dcb

**Comment by marinkobabic** [comment]
Yes it works fine, The problem is that I'm testing on Windows 10 x64 where you don't have this issue?

**Comment by taruti** [comment]
MS used to have VMs for testing IE that included a Windows 7 image.

Yes, this seems Windows 7 specific.

**Comment by marinkobabic** [comment]
So I will setup Windows 7 x64 :smile: I agree with your changes but I have no idea why FileObject, vcb or dcb should be null. So I must understand it.

**Comment by taruti** [comment]
Both 32 and 64 bit win 7 seems to be enough for a crash with the branch.

**Comment by marinkobabic** [comment]
You can run mirror using the new version without any issues? Only the stress tests causes the driver to fail?

**Comment by taruti** [comment]
In my Windows 7 tests:

Branch | Mirror | Stress test from #230
------------ | ------------- | --------------------
master | ok | crash
#281 | ok | crash less often
#282 | ok | crash less often
FixNullIReference branch | crash fast | crash fast

**Comment by marinkobabic** [comment]
have returned wrong state when the volume is not mounted, please can you try again just the mirror?

**Comment by taruti** [comment]
https://github.com/marinkobabic/dokany/tree/FixNullIReference with the second patch fails to compile:
```uninitialized local variable 'ccb' used``` in volume.c line 197. Is there a commit missing from there?

**Comment by marinkobabic** [comment]
It’s fixed



Von: Taru Karttunen [mailto:notifications@github.com]
Gesendet: Mittwoch, 6. Juli 2016 15:55
An: dokan-dev/dokany <dokany@noreply.github.com>
Cc: Babic Marinko <marinko.babic@ruf.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [dokan-dev/dokany] sys: Add IsUnmounting to the DCB (#282)



https://github.com/marinkobabic/dokany/tree/FixNullIReference with the second patch fails to compile:
uninitialized local variable 'ccb' used in volume.c line 197. Is there a commit missing from there?

**Comment by taruti** [comment]
After the third commit it compiles but crashes instantly also with mirror.

**Pull request closed without merging**
