### PR TITLE
Keepalive activation race condition in Dokan DLL

### LINKED ISSUE #776: Keepalive activation race condition in Dokan DLL
# Environment
 * Windows version: Windows 10 Pro 
 * Processor architecture: intel x64
 * Dokany version: 1.2.1.2000
 * Library type (Dokany/FUSE): Dokany DLL
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
There seems to be a race condition in the `DokanMain` function of the DLL (project: `dokan`, file: `dokan.c`): If the keepalive activation `DeviceIoControl(...FSCTL_ACTIVATE_KEEPALIVE...)` runs before a worker thread performs `DeviceIoControl(...IOCTL_EVENT_WAIT...)` (in `DokanLoop`) then the keepalive activation fails. You can reproduce by adding a sleep in the beginning of `DokanLoop` or not starting the threads altogether. The race condition doesn't happen in debug mode because the debugging print after mounting takes enough time for the worker thread to call `DeviceIoControl`.

On a separate note, this comment exists in `DokanMain`:
```
    // We don't consider this a fatal error because the keepalive handle is only
    // needed for abnormal termination cases anyway.
```
But it seems that if the keepalive activation fails then `DeviceIoControl(...IOCTL_EVENT_WAIT...)` in the worker thread(s) will time out (during inactivity) returning `ERROR_OPERATION_ABORTED` (995) and stopping the worker thread. I don't know if this is the correct behavior, but either the keepalive activation must be made obligatory or the worker thread should be able to recover from this error.

### PR DESCRIPTION
**Pull request by TrabacchinLuigi**
Fixes #776 #782 #779 .

### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the existing documentation
- [x] My changes generate no new warnings
- [ ] I have updated the change log (Add/Change/Fix)
- [x] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

- Avoid unpredictable unmount of drives, by ensuring the KeepAlive_handle is valid

All credits goes to @Hasan-Jawaheri for the code changes i just made the pull request and some tests to speed up things

### CODE REVIEW

**Comment by Rondom** [comment]
You can give credit in the commit itself using git commit --author="name <email>"

**Comment by TrabacchinLuigi** [comment]
Argh didn't knew that, I'll try to redo it, but I have small time today...

**Comment by TrabacchinLuigi** [comment]
I was wandering: can this moved to a method and be tested somehow?

**Comment by Liryna** [comment]
Hi @TrabacchinLuigi ,

I understand this fix, but probably we should look deeper into this and understanding what’s happening and apply a proper fix.

**Comment by TrabacchinLuigi** [comment]
IMHO this fix solve a nasty situation in a released driver with no significant downsides, I would rather merge this, test, release, and finally look deeper

**Comment by taruti** [comment]
Having a release with some fix for this would be very nice.

**Comment by Liryna** [comment]
Please see https://github.com/dokan-dev/dokany/issues/776#issuecomment-470262303
I will try to make a release with it after the feedback as fast as I can 👍

**Pull request closed without merging**
