### PR TITLE
Flush any opened files before doing a rename

### PR DESCRIPTION
**Pull request by marinkobabic**
Fix here described issue https://github.com/dokan-dev/dokany/issues/436

### CODE REVIEW

**Comment by Liryna** [comment]
Hi @marinkobabic ,

Thanks a lot for the PR and taking the time on this issue 👍 as always ! 🍺

**Comment by Liryna** [comment]
@marinkobabic performance question, can we not just flush file in the directory ?

**Comment by marinkobabic** [comment]
@Liryna That would make sense. I flushed all of them just because it was simpler to implement.

**Comment by Liryna** [comment]
Ok I see @marinkobabic do you plan to make a patch for it ? Or I create an issue to remind ?

**Comment by marinkobabic** [comment]
@Liryna 
Here you have the refactored code. Please do a carefully review of the code https://github.com/dokan-dev/dokany/pull/462

**Pull request merged**
