### PR TITLE
add dokan_vector.h to installed header files

### PR DESCRIPTION
**Pull request by bailey27**
added dokan_vector.h to both x86 and x64 installs

### CODE REVIEW

**Comment by bailey27** [comment]
I changed KeyPath to no for those entries.

**Comment by Liryna** [comment]
Hi @bailey27,

Thank for the PR ! Yes, the changes are correct ! ❤️ 
Appveyor red status seems to come from a crash during the test.

Can you just rebase into one commit and I will merge it 👍

**Comment by bailey27** [comment]
@Liryna 

Thanks for approving it.  I've rebased it into one commit.

**Comment by Liryna** [comment]
Perfect @bailey27 ! Thanks you !  🥇

**Pull request merged**
