### PR TITLE
Register callback for dismount

### PR DESCRIPTION
**Pull request by LTRData**
Added two API functions `DokanRegisterWaitForFileSystemClosed` and `DokanUnregisterWaitForFileSystemClosed`, for registering and unregistering a callback to be called when the `DeviceClosedWaitHandle` is set. Makes it easier to register work to be done after dismount without letting a thread wait for it.

New feature.

### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the existing documentation
- [x] My changes generate no new warnings
- [ ] I have updated the change log (Add/Change/Fix)
- [x] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by Liryna** [comment]
Hi @LTRData ,

That's a very good idea of API! Could you add them to the header with some documentation like the existing ones ?
https://github.com/dokan-dev/dokany/blob/ce8b8229ad8262f920ca8d284448c1fe10e46cae/dokan/dokan.h#L878

**Comment by LTRData** [comment]
> Hi @LTRData ,
> 
> That's a very good idea of API 🥇  ! Could you add them to the header with some documentation like the existing ones ?
> https://github.com/dokan-dev/dokany/blob/ce8b8229ad8262f920ca8d284448c1fe10e46cae/dokan/dokan.h#L878

Yes I'll do that! 👍

**Comment by LTRData** [comment]
Done!

**Comment by Liryna** [comment]
Thank you very much @LTRData !
I am currently blocked by https://github.com/dokan-dev/dokany/issues/648 until I can make a release including your changes. Hopefully, it can happen in the next days.

**Comment by LTRData** [comment]
Thank you!

**Pull request merged**
