### PR TITLE
Call FindFiles if FindFilesWithPattern returns STATUS_NOT_IMPLEMENTED

### PR DESCRIPTION
**Pull request by accorp**
Small enhancement to FindFiles without breaking API compatibility.

### CODE REVIEW

**Comment by Liryna** [comment]
Hi @accorp,

Thank you for your pull request !

I understand in which case this fix could be useful but,
is it not 'strange' that the FindFilesWithPattern would be implemented and return STATUS_NOT_IMPLEMENTED ?

**Comment by accorp** [comment]
Not as strange as to give callbacks possibility to return result as NTSTATUS and disallow one of its proper code. :smile: BTW In Dokan.NET binding there is NotImplemented as one of DokanResult constant.

This issue I faced trying to write full featured class-based dokan wrapper for Delphi/Lazarus. Currently, FindFilesWithPattern hides FindFiles if it is set in DOKAN_OPERATIONS. If all callbacks will be able to return STATUS_NOT_IMPLEMENTED it gives control from designtime to runtime, which is required for high-level programming. I think it will be useful for other bindings as well.

As a possible workaround, I can use separate DokanOperations for each mount, or make call to FindFiles from FindFilesWithPattern and then use DokanIsNameInExpression, or not support FindFilesWithPattern at all (like Dokan.NET binding does), but I don't like any of them.

**Comment by Liryna** [comment]
Ok that make it more clean :+1: 
Thanks for the clear answer !

It even look more like how we use EnumerateNamedStreams in .NET as you say.

I have also add a ticket for the Dokan.NET wrapper FindFilesWithPattern that is missing for now.
https://github.com/dokan-dev/dokan-dotnet/issues/60

**Comment by accorp** [comment]
Great, thanks!

**Pull request merged**
