### PR TITLE
FUSE - Fix return correct status when file is FILE_OVERWRITE_IF or FILE_OPEN_IF successfully

### LINKED ISSUE #667: When dokan_fuse is used, the error code returned by the call to the windows API createfile function is incorrect when the file exists
Feature request can skip this form. Bug report **must** complete it. `Check List` must be 100% match or it will be automatically closed without further discussion. Please remove this line.

# Environment
 * Windows version: 
 * Processor architecture: 
 * Dokany version: 
 * Library type (Dokany/FUSE): 
 
# Check List
  - [x ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x ] I can always reproduce the issue with the provided description below.
  - [x ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
File exists, call the windows API createfile function; dwCreationDisposition fill CREATE_ALWAYS. Normally, the error code should return ERROR_ALREADY_EXISTS (183), but will always return 0 after using dokan_fuse.
# Logs
Please attach in separate files: mirror output, library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan).
In case of BSOD, please attach minidump or dump analyze output.

### PR DESCRIPTION
**Pull request by linyuan870**
Fixes #667  .

### Checklist

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the existing documentation
- [x ] My changes generate no new warnings
- [x ] I have updated the change log (Add/Change/Fix)
- [x ] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by Liryna** [comment]
Hi @linyuan870 ,

SetLastError was the previous way to give information to the dokan library.
https://github.com/dokan-dev/dokany/pull/130 Fuse has not been updated for this case since

Now it is `STATUS_OBJECT_NAME_COLLISION` that need to be returned
https://github.com/dokan-dev/dokany/blob/83be68351c70d916e58bdae8e3424e521fe07b04/dokan/create.c#L257

Therefor, all SetLastError  could be even removed.

In your PR, you return ***always*** `win_error(STATUS_OBJECT_NAME_COLLISION, true);` without calling `do_open_file`. It should be called and return `win_error(STATUS_OBJECT_NAME_COLLISION, true);` in success.

**Comment by linyuan870** [comment]
@Liryna 
I think you should have no problem before that, but I use your change has been returned 0.
I think it is if (res == 0 & & .....) This condition is not met, the above call do_open_file function does not return after res == 0.

**Comment by linyuan870** [comment]
@Liryna 
**fusemain.cpp :** impl_fuse_context::create_file

**Comment by Liryna** [comment]
@linyuan870 Can you print the return value of 
https://github.com/dokan-dev/dokany/blob/86a52bfa5a8239d9dfc439bde7420398cba7f265/dokan_fuse/src/fusemain.cpp#L557
I would expected to be this one to be called in our case.

**Comment by Liryna** [comment]
Thank you @linyuan870 , -1073741771 "is the correct value".
I changed the error type to long https://github.com/dokan-dev/dokany/commit/359f0853024658522ff1203a3e78a7c026b67b79
https://github.com/dokan-dev/dokany/commit/90c02cdc2a3e0c7ffbdff8d785fb3d3cbb56cf62

Can you try with it ?

**Comment by linyuan870** [comment]
@Liryna 
Unfortunately not.
I use return win_error (STATUS_OBJECT_NAME_COLLISION, true); replace
res = win_error (STATUS_OBJECT_NAME_COLLISION, true); is successful, the front also called do_open_file function, you can change it?

**Comment by Liryna** [comment]
@linyuan870 
```
      long res = do_open_file(file_name, share_mode, access_mode, dokan_file_info);
      if (res == 0 &&
        (creation_disposition == FILE_OVERWRITE_IF ||
        creation_disposition == FILE_OPEN_IF)) {
        return win_error(STATUS_OBJECT_NAME_COLLISION, true);
      }

      return res;
```
Like this so ?

What do you mean by "the front also called do_open_file function" ? can you link this call ?

**Comment by linyuan870** [comment]
@Liryna  YES

**Comment by Liryna** [comment]
Perfect @linyuan870  👍 Thank you !
https://github.com/dokan-dev/dokany/commit/1394841c806bc1992a412d142b29132284e4249a

**Pull request closed without merging**
