### PR TITLE
Add ARM builds to AppVeyor(and pry that ARM SDKs are properly installed there)

### PR DESCRIPTION
**Pull request by woachk**
First attempt...

### CODE REVIEW

**Comment by woachk** [comment]
ARM SDKs work fine on AppVeyor :)
Maybe ready for merging?

**Comment by Liryna** [comment]
Ah great :+1: I just don't have my windows with me, will do the test later today when will have it.
Will also try to add the wix for it. Will I need to download something to add ARM for VS (maybe it is simply on the iso) ?

**Comment by kika123** [comment]
@Liryna for ARM32, you don't need to add anything special normally, but I don't think that WiX itself supports ARM at all(there are examples of working programs using it, but I don't think that they merged it to mainline WiX)...

**Comment by kika123** [comment]
in VS2017, you'll need to install the ARM compiler in Advanced features or to install UWP support, in which case ARM will be selected automatically

**Comment by woachk** [comment]
@Liryna should I attempt WiX again? :)

**Comment by Liryna** [comment]
@woachk Build perfectly on my side 👍 
About wix, I found nothing about arm and wix. Package seems like to have platform arm variable http://wixtoolset.org/documentation/manual/v3/xsd/wix/package.html but no idea if this is working.

Otherwise, can just rebase all your commit into one 😃 ?

**Comment by woachk** [comment]
@Liryna yeah, you can rebase all the commits into one ;)
Yeah, there is ARM support, but a C:\Program Files (x86)\WiX Toolset v3.10\bin\difxapp_arm.wixlib isn't shipped by default as all, maybe it will have to be done without it(I actually have an idea ;)

**Comment by Liryna** [comment]
@woachk You can only rebase the changes :D otherwise it will look like I did the work

**Comment by woachk** [comment]
@Liryna how? I'm a Windows guy and the only Git interface that I really know is the Visual Studio Git client. :P I'm trying and I utterly failed it seems, tring to clone again

**Comment by woachk** [comment]
@Liryna yay, ended up cloning the repo, doing an xcopy, then running git add to have one single commit ;)

**Comment by Liryna** [comment]
@woachk if you are using tortoise git, go on commit log, select all your commit and you have possibility with a rights click on them to merge into one.

**Comment by Liryna** [comment]
Merged here: https://github.com/dokan-dev/dokany/pull/446

**Comment by Rondom** [comment]
The command-line way, for those that are interested:

    $ git rebase --interactive <commitref>

This will open a text-editor with all the commits since the commit-ref. In this case, you are fine by using the revision where you branched off, i.e. `master` if you have not pulled in newer changes or want to rebase your commits in your branch on top of the newly updated master without creating a merge-commit.

By editing the text, you can
 * reorder the sequence of commits (by changing the order of the individual lines)
 * `squash` (i.e. merge with the previous commit)
 * `drop` commits (removing a line works as well)
* `reword` (i.e. edit commit-msg)
 * `edit` commit contents (you will be dropped back to shell, where you can `git add` and `git commit --amend`. Once your are done, use `git rebase --continue` to proceed with the next commit)

I have yet to find a GIT GUI that does this in a nicer way than this, but "nice" is in the eye of the beholder and I am a command-line-guy that likes text-editors ;-)

For modifying authorship information the following parameter to git commit is useful. 

       --author=<author>
           Override the commit author. Specify an explicit author using the standard A U Thor <author@example.com>
           format. Otherwise <author> is assumed to be a pattern and is used to search for an existing commit by that
           author (i.e. rev-list --all -i --author=<author>); the commit author is then copied from the first such
           commit found.

**Pull request closed without merging**
