### PR TITLE
Resolve hang described in issue #554

### PR DESCRIPTION
**Pull request by benpye**
This should resolve the hang mentioned in #554 . Dokany has a few incorrect bounds checks. I am submitting this PR to get a build that I can verify the issue is resolved in.

### CODE REVIEW

**Comment by benpye** [comment]
Quick test with mirror.exe and this isn't hanging any more.

**Comment by Liryna** [comment]
Hi @benpye ,

Thank you for the PR !
So you were able to reproduce the issue with the commit before your fix ?

**Comment by benpye** [comment]
Yeah, I can still repro with the current master. Looks like the check I linked to be fixed was the wrong one, I think CTRL+F failed me. I'm pretty sure it's the one within `IOCTL_MOUNTDEV_QUERY_DEVICE_NAME` causing the hang, as indicated by the logs and WinDbg.

**Comment by Liryna** [comment]
Alright @benpye !
Thanks a lot again for looking at this fixing the issue 👍 ❤️ !

**Comment by phillijw** [comment]
@benpye You're the hero we don't deserve

**Pull request merged**
