### PR TITLE
Fixed an issue with DokanUnmount() failing to unmount a drive

### PR DESCRIPTION
**Pull request by Corillian**
This fix also applies to dokanctl.exe /u
Enabled debug information for dokan.dll and dokannp.dll when compiling
in Debug so that I could debug
Issue #57

### CODE REVIEW

**Comment by Liryna** [comment]
Thanks for this PR :heart: and taking the time in your issue :D !

To finish to normalizing mount paths, don't you think we should also change the mount function to force the `M:\` ?
https://github.com/Corillian/dokany/blob/InvestigateHang/dokan_mount/mount.c#L263

And also fix the mirror :smile: https://github.com/Corillian/dokany/blob/InvestigateHang/dokan_mirror/mirror.c#L51

**Comment by Corillian** [comment]
Hey sorry got sidetracked with working on other stuff. Yeah I can add normalization to mirror and mount.

**Comment by Corillian** [comment]
Ok I added the normalization to mounter.exe as that seems to be the only place where it matters. Drive letter names are normalized to the format "C:\" upon insertion into `g_MountList` as well as when `g_MountList` is being searched. I also updated this branch to the latest on master. Let me know if I missed anything.

**Comment by Liryna** [comment]
Thank you @Corillian and for taking the time !
I will try to take a look this weekend :)

**Comment by Liryna** [comment]
Perfectly working on my side after test !
Thank a lot @Corillian for your contributions in the dokan project !

Normalizing the mount point will help a lot the dev & users of dokan !

**Pull request merged**
