### PR TITLE
fuse:fix stat define and add network drive map

### PR DESCRIPTION
**Pull request by gang929**
use volname for network drive name
add option use network drive
redefine stat for binary compatible

### CODE REVIEW

**Comment by Maxhy** [comment]
Two remarks:
 - I think you're setting volume name from registry because you don't want to use UNC here or didn't registered the Network Provider (there is indeed a small today, to setup a custom volume name on network mount point, you have to setup a UNC redirector)? If so, this shouldn't be specific to FUSE but generally available on Dokan Library. But I also believe it would be better to refactor UNC redirector setup logic to avoid to use registry and duplication with Network Provider (be aware of current bug https://github.com/dokan-dev/dokany/issues/236#issuecomment-219688455). What do you think?
 - When your PR is ready, is better to clean git history to one commit per change compared to base (see https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/).

Thanks @gang929.

**Comment by gang929** [comment]
Because i want use the command line parameter to set the Network Map Drive Name each time, so use the parameter volame for the network drive name. And, I didn't find the code to set the network drive name("DAV RPC SERVICE")

**Comment by Maxhy** [comment]
I updated the wiki to explain better how a network drive label could be setup: https://github.com/dokan-dev/dokany/wiki/API#network-provider
I agree your code to setup from registry could have its interest, but it shouldn't be on fuse library only then.

Otherwise, I'm not sure to understand your binary compatibility change here. I know it is related to #234 but could you explain what is in details the issue and how your changes are fixing it here? I don't see the value of these kind of defines here, probably just a lack of knowledge from my side. Thanks.

**Comment by gang929** [comment]
sorry, I  only know very little about network-provider,  I didn't know how to set an UNC Name for Network Redirector, so ,I directly setup drive label from registry. 
the `dokanctl.exe /i n` code can not set unc name with mapping a drive each time 
 @Maxhy , you can explain more about?  thanks!

about https://github.com/dokan-dev/dokany/issues/234 
In VS2015(build with x86), the mode_t and nlink_t is 4bytes, but In mingw32, they are 2bytes,  otherwise, the timespec is 16bytes in VS2015, but 8bytes in mingw.  Maybe, the cygwin is same as VS2015.
so, I think the stat should be defined by fixed bytes for all field.

**Comment by gang929** [comment]
the command `C:\Program Files\Dokan\Dokan Library-1.0.0\x86>sample\mirror\mirror.exe /r c: /l k /n` 
will mirror c: to k:, but the label sometimes is DOKAN,
when mirror to other driveletter(I, L, M ...)  sometimes is other unkown name (cg DAV RPC SERVICE， or xx\adfs\cvv)， it seems that this is a  bug?

**Comment by Liryna** [comment]
@gang929 UNC can be set at the mount: https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L1335

About label that sometimes change, can you make a test with the last commit: https://github.com/dokan-dev/dokany/commit/d3ecfb0e5d327092113430bfd7b27ee605860081
It can probably fix the behaviour. If not, can you describe a way to reproduce it ?

For binary compatibility, I don't understand why you compare visual studio and cygwin. The way it work, if your filesystem is build with cygwin, it has to use the dokan fuse build with cygwin. That's why the dokan installer has VS/Cygwin/msys version of the dokan fuse. With this you will have the same size of stat member no ?

**Comment by gang929** [comment]
I rebuild  with the last commit:  https://github.com/dokan-dev/dokany/commit/d3ecfb0e5d327092113430bfd7b27ee605860081  and test 
`C:\Program Files\Dokan\Dokan Library-1.0.0\x86>sample\mirror\mirror.exe /r c: /l m /n /u ffff  `
in windows explorer, it show as 


For binary compatibility,  the dokanfuse1.dll build with VS2015,  I build wdfs with dokanfuse1.dll in mingw32.
if define fuse_stat.st_mode/st_nlink/st_atime... as below 
```
     mode_t        st_mode;
     nlink_t       st_nlink;
...
    timestruc_t   st_atim;
```
so , the sizeof(fuse_stat)  in dokanfuse1.dll  not equal sizeof(fuse_stat) in wdfs, because In VS2015(build with x86), the mode_t and nlink_t is 4bytes, but In mingw32, they are 2bytes, otherwise, the timespec is 16bytes in VS2015, but 8bytes in mingw.

**Comment by gang929** [comment]
@Liryna  how to set unc name or network drive label?

**Comment by Liryna** [comment]
@gang929 

UNC:

> mirror.exe /r c:\Users /l m /n /u \localhost\mytest

You can acces it by `\\localhost\mytest`

Network drive label is set by `GetVolumeInformation`
https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L1125

**Comment by gang929** [comment]
@Liryna 
`GetVolumeInformation ` is only  correctly with `mirror.exe /r c: /l m`, when `mirror.exe /r c: /l m /n` is display error as

**Comment by Liryna** [comment]
From my point of view, I don't think we should add network option in libfuse since it does not exist in libfuse.

I will try to reproduce your issue @gang929 with wrong label name using network.

**Comment by Maxhy** [comment]
Ok according to the discussion I will summarize this PR state as following:

 - Network label name: current method to set network label name is using UNC and proposed registry method should be avoided for now. A buffer related bug seems to exist and should be fixed.
 - stat64_cygwin structure is incompatible between compilers but this shouldn't be changed. This struct is generally used by fuse fs implementation with system function (eg. lstat), those are also dependent to each compiler (cygwin, msys2, ...). Your fuse fs should link with dokanfuse built with the same compiler.
 - My opinion about network option on libfuse is that it should indeed be implemented as fuse_config structure doesn't impact fs implementation (and if using *Windows only fuse options* a #ifdef check could be done).

**Comment by Liryna** [comment]
Hi @gang929 ,

I have import and clean your commit for network drive option: https://github.com/dokan-dev/dokany/commit/8e4590c2a4b93a8d45366660c54e64c66975c39d
Thank you again for your contribution and your time !

I have also try to reproduce the issue with the mirror network name :cry: but impossible to get the same behaviour as you. If you have new informations about it, please open an issue ! :heart:

**Pull request closed without merging**
