### PR TITLE
Update dokan.c

### PR DESCRIPTION
**Pull request by justanotheranonymoususer**
Typo

### CODE REVIEW

**Comment by Liryna** [comment]
Good :D ?

**Comment by justanotheranonymoususer** [comment]
Pardon?

**Comment by Liryna** [comment]
I wanted to know if you have any other typo to fix.

**Comment by justanotheranonymoususer** [comment]
Oh. That's all for now. Just saw them with a VS extension that highlights typos while browsing that file. I guess that there are many more, if I found so many in just one file :), but it's not convenient to fix these through the GitHub editor, and I don't have a Git client at hand to submit a proper pull request.

**Comment by Liryna** [comment]
Oh ok :D !

**Pull request merged**
