### PR TITLE
created updatereadme.md

### PR DESCRIPTION
**Pull request by bhardwajanish**
I fixed the grammar and language. I am a native English speaker.

### CODE REVIEW

**Comment by bhardwajanish** [comment]
I don't understand...What would you like me to do?

**Comment by sm4rk0** [comment]
@bhardwajanish You should:
* close this PR, and delete the branch in your repo
* open [this link ](https://github.com/dokan-dev/dokany/blob/master/README.md) in new tab
* click the pen button in upper right corner (with "Fork this project and edit this file" tooltip)
* edit existing text (without removing the badges, images, links, etc)
* Commit and create a PR

**Comment by sm4rk0** [comment]
Updated the comment in order to preserve your current PR not to lose the changes you already made.

**Comment by Rondom** [comment]
I suggest to wait until the other PRs are merged to prevent conflicts.

@sm4rk0 I am not too familiar with GitHub-webinterface (never really used it), but is it not possible to update this PR without closing and creating PRs? I mean, the usual workflow when working locally is to push (force-push, if necessary) to the same branch, keeping all history and discussion in one PR.

**Comment by sm4rk0** [comment]
@Rondom I'm also not familiar (enough) with the web interface. That's why I proposed probably longer, but safer way.

**Comment by Liryna** [comment]
@sm4rk0 Feel free to recreate a proper pull request 👍

**Comment by sm4rk0** [comment]
Good idea. All changes proposed here are already included in #601 and #603.

**Pull request closed without merging**
