### PR TITLE
Initial commit for WiX driver MSIs and Bootstrapper setup

### PR DESCRIPTION
**Pull request by js69**
As sent to Liryna:

This is a first version of dokan_wix, a solution with WiX to build MSI setup files for the drivers and a standard Bootstrapper.

Requirements to build the WiX projects:

1.	Download and install the current WiX 3.10.1.2213 from http://wixtoolset.org/releases/
2.	Download the VC 2015 Runtimes  and save them to the dokan_wix\Bootstrapper\Redist\VCRedist_2015\ folder. They are required for the build process, but will not be included in the bootstrapper unless you set <?define Compressed="no" ?> in version.xml to “yes”. 

https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe

https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe

        Expected filenames and sizes:

14.572.000 bytes                             vc_redist.x64.exe
13.767.776 bytes                             vc_redist.x86.exe

The bootstrapper setup-executable will automatically try to download the redists from the URL above when necessary or use files with these exact names directly if they exist in the same folder as the bootstrapper DokanSetup.exe. I believe a large DokanSetup redist build should not be necessary anymore.

The WiX projects expect the same input files as the NSIS project did, a successful build of the Dokan solution with e.g. ..\Win32\Win10Release\dokan.sys
Driver installation is done by executing in a custom action dokanctl /i n followed by dokanctl /i a just like in the NSIS.

The solution currently does not include any code signing step for MSIs and the setup executable.

dokan_wix\version.xml holds parameters for product codes and version numbers. I’d be able to provide a tool to automatically update this file if you like.

Project output files will be created in dokan_wix\bin (MSIs for x64 and x86) and dokan_wix\Bootstrapper\bin (DokanSetup.exe bootstrapper).

The MSIs include a custom action to check for a previously installed NSIS version of the driver and will error out accordingly, asking users to uninstall the obsolete version first.

I’ve tested the package so far on Win7, Win 8.1 and Win 10, all 64 bit only.

License is MIT where nothing else applies.

Question to the knowledgable: there is probably a specific reason the uninstall with dokanctl can not remove the driver without the need for a reboot. Is this because of the Mounter service? If so, I could provide some DeleteServiceFromSCM code that would work without a reboot requirement.

### CODE REVIEW

**Comment by Liryna** [comment]
:+1:

**Comment by Corillian** [comment]
Commit https://github.com/js69/dokany/commit/70bd0f25dd6b52fdc81e0750f7ccec874c8657f0 does not properly install the driver per the following: https://msdn.microsoft.com/en-us/library/windows/hardware/ff540376(v=vs.85).aspx

**Comment by Liryna** [comment]
Hello @js69 ,

I have some error to build the installer :cry:
I only build the solution, am I doing something wrong ?
```
1>------ Rebuild All started: Project: WiXCA, Configuration: Debug x86 ------
1>  Searching for custom action entry points in WiXCA.dll
1>      Loaded dependent assembly: C:\Program Files (x86)\WiX Toolset v3.10\SDK\Microsoft.Deployment.WindowsInstaller.dll
1>      CheckDokanNSISInstalled=WiXCA!WiXCA.CustomActions.CheckDokanNSISInstalled
1>      ExecuteInstall=WiXCA!WiXCA.CustomActions.ExecuteInstall
1>      ExecuteUninstall=WiXCA!WiXCA.CustomActions.ExecuteUninstall
1>      DeleteBundleItems=WiXCA!WiXCA.CustomActions.DeleteBundleItems
1>  Searching for an embedded UI class in WiXCA.dll
1>  Modifying SfxCA.dll stub
1>  Copying file version info from C:\Users\liryna\Desktop\dokany\dokan_wix\WiXCA\obj\x86\Debug\WiXCA.dll to C:\Users\liryna\Desktop\dokany\dokan_wix\WiXCA\obj\x86\Debug\WiXCA.CA.dll
1>  Packaging files
1>      WiXCA.dll
1>      Microsoft.Deployment.WindowsInstaller.dll
1>      CustomAction.config
1>  MakeSfxCA finished: C:\Users\liryna\Desktop\dokany\dokan_wix\WiXCA\obj\x86\Debug\WiXCA.CA.dll
1>  WiXCA -> C:\Users\liryna\Desktop\dokany\dokan_wix\WiXCA\bin\Debug\WiXCA.dll
2>------ Rebuild All started: Project: DokanMSI_x86, Configuration: Debug x86 ------
2>	C:\Program Files (x86)\WiX Toolset v3.10\bin\candle.exe -dSourceDir=.\Sources -d"DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\\" -dSolutionDir=C:\Users\liryna\Desktop\dokany\dokan_wix\ -dSolutionExt=.sln -dSolutionFileName=Dokan_WiX.sln -dSolutionName=Dokan_WiX -dSolutionPath=C:\Users\liryna\Desktop\dokany\dokan_wix\Dokan_WiX.sln -dConfiguration=Debug -dOutDir=bin\x86\Debug\ -dPlatform=x86 -dProjectDir=C:\Users\liryna\Desktop\dokany\dokan_wix\ -dProjectExt=.wixproj -dProjectFileName=DokanMSI_x86.wixproj -dProjectName=DokanMSI_x86 -dProjectPath=C:\Users\liryna\Desktop\dokany\dokan_wix\DokanMSI_x86.wixproj -dTargetDir=C:\Users\liryna\Desktop\dokany\dokan_wix\bin\x86\Debug\ -dTargetExt=.msi -dTargetFileName=Dokan_x86.msi -dTargetName=Dokan_x86 -dTargetPath=C:\Users\liryna\Desktop\dokany\dokan_wix\bin\x86\Debug\Dokan_x86.msi -out obj\x86\Debug\ -arch x86 -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixDifxAppExtension.dll" -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixUtilExtension.dll" Dokan_x86.wxs
2>	C:\Program Files (x86)\WiX Toolset v3.10\bin\Light.exe -out C:\Users\liryna\Desktop\dokany\dokan_wix\bin\x86\Debug\Dokan_x86.msi -pdbout C:\Users\liryna\Desktop\dokany\dokan_wix\bin\x86\Debug\Dokan_x86.wixpdb -cultures:null -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixDifxAppExtension.dll" -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixUtilExtension.dll" -sice:ICE30 -contentsfile obj\x86\Debug\DokanMSI_x86.wixproj.BindContentsFileListnull.txt -outputsfile obj\x86\Debug\DokanMSI_x86.wixproj.BindOutputsFileListnull.txt -builtoutputsfile obj\x86\Debug\DokanMSI_x86.wixproj.BindBuiltOutputsFileListnull.txt -wixprojectfile C:\Users\liryna\Desktop\dokany\dokan_wix\DokanMSI_x86.wixproj -sw1137 obj\x86\Debug\Dokan_x86.wixobj
2>C:\Users\liryna\Desktop\dokany\dokan_wix\Dokan_x86.wxs(209,0): error LGHT0094: Unresolved reference to symbol 'CustomAction:MsiProcessDrivers' in section 'Product:{65A3A986-3DC3-4C7A-82C3-35DDEE92359D}'.
2>C:\Users\liryna\Desktop\dokany\dokan_wix\Dokan_x86.wxs(219,0): error LGHT0094: Unresolved reference to symbol 'CustomAction:MsiProcessDrivers' in section 'Product:{65A3A986-3DC3-4C7A-82C3-35DDEE92359D}'.
2>C:\Users\liryna\Desktop\dokany\dokan_wix\Dokan_x86.wxs(229,0): error LGHT0094: Unresolved reference to symbol 'CustomAction:MsiProcessDrivers' in section 'Product:{65A3A986-3DC3-4C7A-82C3-35DDEE92359D}'.
2>C:\Users\liryna\Desktop\dokany\dokan_wix\Dokan_x86.wxs(239,0): error LGHT0094: Unresolved reference to symbol 'CustomAction:MsiProcessDrivers' in section 'Product:{65A3A986-3DC3-4C7A-82C3-35DDEE92359D}'.
2>Done building project "DokanMSI_x86.wixproj" -- FAILED.
2>
3>------ Rebuild All started: Project: DokanMSI_x64, Configuration: Debug x64 ------
3>	C:\Program Files (x86)\WiX Toolset v3.10\bin\candle.exe -dSourceDir=.\Sources -d"DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\\" -dSolutionDir=C:\Users\liryna\Desktop\dokany\dokan_wix\ -dSolutionExt=.sln -dSolutionFileName=Dokan_WiX.sln -dSolutionName=Dokan_WiX -dSolutionPath=C:\Users\liryna\Desktop\dokany\dokan_wix\Dokan_WiX.sln -dConfiguration=Debug -dOutDir=bin\x64\Debug\ -dPlatform=x64 -dProjectDir=C:\Users\liryna\Desktop\dokany\dokan_wix\ -dProjectExt=.wixproj -dProjectFileName=DokanMSI_x64.wixproj -dProjectName=DokanMSI_x64 -dProjectPath=C:\Users\liryna\Desktop\dokany\dokan_wix\DokanMSI_x64.wixproj -dTargetDir=C:\Users\liryna\Desktop\dokany\dokan_wix\bin\x64\Debug\ -dTargetExt=.msi -dTargetFileName=Dokan_x64.msi -dTargetName=Dokan_x64 -dTargetPath=C:\Users\liryna\Desktop\dokany\dokan_wix\bin\x64\Debug\Dokan_x64.msi -out obj\x64\Debug\ -arch x64 -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixDifxAppExtension.dll" -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixUtilExtension.dll" -sw1077 Dokan_x64.wxs
3>	C:\Program Files (x86)\WiX Toolset v3.10\bin\Light.exe -out C:\Users\liryna\Desktop\dokany\dokan_wix\bin\x64\Debug\Dokan_x64.msi -pdbout C:\Users\liryna\Desktop\dokany\dokan_wix\bin\x64\Debug\Dokan_x64.wixpdb -cultures:null -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixDifxAppExtension.dll" -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixUtilExtension.dll" -sice:ICE30 -contentsfile obj\x64\Debug\DokanMSI_x64.wixproj.BindContentsFileListnull.txt -outputsfile obj\x64\Debug\DokanMSI_x64.wixproj.BindOutputsFileListnull.txt -builtoutputsfile obj\x64\Debug\DokanMSI_x64.wixproj.BindBuiltOutputsFileListnull.txt -wixprojectfile C:\Users\liryna\Desktop\dokany\dokan_wix\DokanMSI_x64.wixproj -sw1137 obj\x64\Debug\Dokan_x64.wixobj
3>C:\Users\liryna\Desktop\dokany\dokan_wix\Dokan_x64.wxs(210,0): error LGHT0094: Unresolved reference to symbol 'CustomAction:MsiProcessDrivers' in section 'Product:{65A3A964-3DC3-4C7A-82C3-35DDEE92359D}'.
3>C:\Users\liryna\Desktop\dokany\dokan_wix\Dokan_x64.wxs(220,0): error LGHT0094: Unresolved reference to symbol 'CustomAction:MsiProcessDrivers' in section 'Product:{65A3A964-3DC3-4C7A-82C3-35DDEE92359D}'.
3>C:\Users\liryna\Desktop\dokany\dokan_wix\Dokan_x64.wxs(230,0): error LGHT0094: Unresolved reference to symbol 'CustomAction:MsiProcessDrivers' in section 'Product:{65A3A964-3DC3-4C7A-82C3-35DDEE92359D}'.
3>C:\Users\liryna\Desktop\dokany\dokan_wix\Dokan_x64.wxs(240,0): error LGHT0094: Unresolved reference to symbol 'CustomAction:MsiProcessDrivers' in section 'Product:{65A3A964-3DC3-4C7A-82C3-35DDEE92359D}'.
3>Done building project "DokanMSI_x64.wixproj" -- FAILED.
3>
4>------ Rebuild All started: Project: Bootstrapper, Configuration: Debug x86 ------
4>	C:\Program Files (x86)\WiX Toolset v3.10\bin\candle.exe -dDebug -d"DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\\" -dSolutionDir=C:\Users\liryna\Desktop\dokany\dokan_wix\ -dSolutionExt=.sln -dSolutionFileName=Dokan_WiX.sln -dSolutionName=Dokan_WiX -dSolutionPath=C:\Users\liryna\Desktop\dokany\dokan_wix\Dokan_WiX.sln -dConfiguration=Debug -dOutDir=bin\Debug\ -dPlatform=x86 -dProjectDir=C:\Users\liryna\Desktop\dokany\dokan_wix\Bootstrapper\ -dProjectExt=.wixproj -dProjectFileName=Bootstrapper.wixproj -dProjectName=Bootstrapper -dProjectPath=C:\Users\liryna\Desktop\dokany\dokan_wix\Bootstrapper\Bootstrapper.wixproj -dTargetDir=C:\Users\liryna\Desktop\dokany\dokan_wix\Bootstrapper\bin\Debug\ -dTargetExt=.exe -dTargetFileName=DokanSetup.exe -dTargetName=DokanSetup -dTargetPath=C:\Users\liryna\Desktop\dokany\dokan_wix\Bootstrapper\bin\Debug\DokanSetup.exe -out obj\Debug\ -arch x86 -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixDependencyExtension.dll" -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixUtilExtension.dll" -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixNetFxExtension.dll" -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixBalExtension.dll" Bundle.wxs
4>	C:\Program Files (x86)\WiX Toolset v3.10\bin\Light.exe -out C:\Users\liryna\Desktop\dokany\dokan_wix\Bootstrapper\bin\Debug\DokanSetup.exe -pdbout C:\Users\liryna\Desktop\dokany\dokan_wix\Bootstrapper\bin\Debug\DokanSetup.wixpdb -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixDependencyExtension.dll" -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixUtilExtension.dll" -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixNetFxExtension.dll" -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixBalExtension.dll" -contentsfile obj\Debug\Bootstrapper.wixproj.BindContentsFileList.txt -outputsfile obj\Debug\Bootstrapper.wixproj.BindOutputsFileList.txt -builtoutputsfile obj\Debug\Bootstrapper.wixproj.BindBuiltOutputsFileList.txt -wixprojectfile C:\Users\liryna\Desktop\dokany\dokan_wix\Bootstrapper\Bootstrapper.wixproj obj\Debug\Bundle.wixobj
4>C:\Users\liryna\Desktop\dokany\dokan_wix\Bootstrapper\Bundle.wxs(77,0): error LGHT0103: The system cannot find the file '..\bin\x86\Debug\Dokan_x86.msi'.
4>C:\Users\liryna\Desktop\dokany\dokan_wix\Bootstrapper\Bundle.wxs(87,0): error LGHT0103: The system cannot find the file '..\bin\x64\Debug\Dokan_x64.msi'.
4>Done building project "Bootstrapper.wixproj" -- FAILED.
4>
========== Rebuild All: 1 succeeded, 3 failed, 0 skipped ==========

```

**Comment by js69** [comment]
Hi, I only added some project settings for Release so far, I'll add them for Debug as well (Linker needs to usw the difx wixlib etc) when I'm back at a PC.

Cheers.

**Comment by js69** [comment]
Updated to allow Debug build. Also added pre-Build event to retrieve VC runtimes.

**Comment by Liryna** [comment]
:open_mouth: binary into a repository ?
I think this could be replace by a powershell script in the build event that use Invoke-WebRequest
http://superuser.com/questions/362152/native-alternative-to-wget-in-windows-powershell

Otherwise thank you for the Debug build !
I will make test when I can !

**Comment by Liryna** [comment]
@js69 , sorry for taking time for review your pull request.
I have started to looking into it (also made a pull request on your repository https://github.com/js69/dokany/pull/1).
We want to finish the mount manager feature and after I will make a full test of your installer.

I will need your help about https://github.com/dokan-dev/dokany/issues/129#issuecomment-167096764

**Comment by Liryna** [comment]
Hi @js69 ,

Here my review of the installer:
* If the driver is not installed correctly (because not signed driver for exemple). There is not error displayed. The install succeed and propose to reboot when it should fail.
* Does dokan.inf and dokan.pdb in system32\drivers could be move into install folder ?
* The x86 binaries (dokan.dll mirror.exe,...) seems to not be installed on x64 system.
* `DokanSetup.exe ADDLOCAL=All` does not seems to install PDB files in Dokan\DokanLibrary\pdb. 

Otherwise the installer seems to work perfectly :+1: Great job !

**Comment by Liryna** [comment]
@js69 , I just made all changes https://github.com/dokan-dev/dokany/commit/78b94934eb6a9e1eaea7db358959fe8bb0473126 . It would be great if you could make the changes also in your installer.
See `install.nsi`changes

**Comment by js69** [comment]
Implementing the changes now.

"The x86 binaries (dokan.dll mirror.exe,...) seems to not be installed on x64 system."

Why would we want to install them on x64? That seems to be a use case for developers only and they will compile from source anyway.

**Comment by Liryna** [comment]
Yes, it is for developer who want to build a x86 application using dokan on their x64 system.
I am not sure they will want to clone the repository with a specific tag and rebuild the library.
It is more simple for them to find directly the library build and include in the installer as we now do.

**Comment by js69** [comment]
I've commited a new version for the tasks you mentioned above.

The following issue cannot easily be resolved (and is only valid for developers who forget to sign, I guess):

"If the driver is not installed correctly (because not signed driver for exemple). There is not error displayed. The install succeed and propose to reboot when it should fail."

When the driver is unsigned, on WIn10 MSIExec will show a reboot suggestion first and an error for the unsigned driver only later on, after the user denies to reboot. This MSI issues would need to be worked around in a custom action by checking the driver file first before DIFx starts.

**Comment by Liryna** [comment]
Thank you @js69 , I will try to review your changes in the next days !

Is there a reason that you dual-sign sha1/sha2 for prod ? sha2 is compativle with all supported OS from what I see.
http://blogs.technet.com/b/pki/archive/2010/09/30/sha2-and-windows.aspx

**Comment by js69** [comment]
The driver would not load in Win10 for me unless it was signed with Visual Studio driver signing - and that one apparently can not use SHA2 on everything (including timestamp).

Not sure what parameters would be needed for signtool to do the same as Visual Studio driver signing does.

**Comment by Liryna** [comment]
Strange because I am already signed it with sha256 myself
https://github.com/dokan-dev/dokany/commit/16d78c69b1e6ef365313fc8a51d34113f81142a2

**Comment by js69** [comment]
With Visual Studio Driver Signing? You can only set the File Digest Algorithm, but not Timestamp algorithm there as far as I can tell.

Check if your .sys file's digital certificate timestamp actually shows SHA256 as digest algorithm (in Countersignature details).

**Comment by Liryna** [comment]
Didn't test with Visual studio. Directly with https://github.com/dokan-dev/dokany/blob/16d78c69b1e6ef365313fc8a51d34113f81142a2/sign.bat

**Comment by js69** [comment]
Do I need to import something for the GoDaddy cert? When I try the sign.bat I receive the error: "SignTool Error: No certificates were found that met all the given criteria."

I disabled Driver Signing in the project.

**Comment by Liryna** [comment]
The script is using directly our certificat. I gave the script as exemple.

You should try to build with auto sign from VS and after sign yourself to be sure that it is correctly made.

**Comment by js69** [comment]
Is your certificate still SHA1? The SHA2 driver compatibilty problem will not occur with that one I guess.

**Comment by Liryna** [comment]
Our cert is SHA2. I made the test again. I can assure you that it work.

**Comment by js69** [comment]
With SHA2-only signed and timestamped driver file on Win10 the "Digitally signed driver" error appears.

> DIFXAPP: INFO:   ENTER:  DriverPackageInstallW
> DIFXAPP: INFO:   Copied 'dokan.inf' to driver store...
> DIFXAPP: INFO:   Commiting queue...
> DIFXAPP: INFO:   Copied file: 'C:\Program Files\Dokan\DokanLibrary\driver\dokan-1.sys' -> 'C:\Windows\system32\DRVSTORE\dokan_527DE26DAC757CA445D6E4F281C532388DFF74E4\dokan-1.sys'.
> DIFXAPP: INFO:   Installing INF file "C:\Windows\system32\DRVSTORE\dokan_527DE26DAC757CA445D6E4F281C532388DFF74E4\dokan.inf" of Type 2.
> DIFXAPP: INFO:   Installing File System Driver 'C:\Windows\system32\DRVSTORE\dokan_527DE26DAC757CA445D6E4F281C532388DFF74E4\dokan.inf'
> DIFXAPP: ERROR:  Unable to start service 'dokan' because of error 0x241
> 
> 

With a dual SHA1 and SHA2 driver this does not happen.

If your certifcate is the one present on the Dokan beta installers with thumbprint ‎3e c9 3b f9 43 a8 34 27 ef 6c b7 c9 cd ec 54 44 75 0d 30 a8, it is still SHA1.

**Comment by Liryna** [comment]
I installed driver by hand with dokanctl. can you try with it ?
I didn't test with installer for now.

Our certif has been renew some days before and is now sha2. (the last 
beta use the old one)

**Comment by js69** [comment]
I believ you that it will/might work with dokanctl because the routine in there probably doesn't enforce Microsofts Authenticode policy but I think the driver should be installed according to MS guidelines.

It's not a big issue to dual sign it.

**Comment by Liryna** [comment]
Hi @js69 ,

I have added your installer into the master https://github.com/dokan-dev/dokany/commit/943a5d5c6551bc5085317c50d975bd8db55e73ac

I had to import the installer myself because the pull request history issue with past merge (64 files changed not linked with the installer).

It work very well for me ! There is probably some files that I will move later. But it is ready for use !

Otherwise I had to rewrite post build sign to fit our cert :cry: I also made the test with driver sign sha1/sha2. On my win10, I have no problem when the drive is only signed sha2. For the next release, it would be nice if you can tell me if it work on your side too.

Thank you again for all the time you have taken for making this installer ! We finally did it :smile:

**Pull request closed without merging**
