### PR TITLE
fix pageio dead lock

### LINKED ISSUE #625: deadlock in FlushFcb
# Environment
 * Windows version: windows 10 170327-1835
 * Processor architecture: i7-4710HQ
 * Dokany version: latest version
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
there are some .ico files in the folder，browse this directory at the same time using three of explorer window, This may cause explorer window to hangs.

https://pan.baidu.com/s/1jH5FzQu     
This link has some ICO file that can reproduce the problem

i debug this problem， found it is deadlock in two of threads below:

thread 1:

ffffc480`a28b3dd0 fffff800`ab44846c : ffffc480`00000000 00000000`00000001 ffffc480`a28b4270 fffff80e`0a4be000 : nt!KiSwapContext+0x76
ffffc480`a28b3f10 fffff800`ab447f0f : ffffe487`b4053800 ffffe487`b4053900 ffffe487`b34b6f80 00000000`00000000 : nt!KiSwapThread+0x17c
ffffc480`a28b3fc0 fffff800`ab44a1b8 : ffffc480`00000000 ffffe487`b18f1c90 00000001`000000fb ffffe487`b4053800 : nt!KiCommitThreadWait+0x14f
ffffc480`a28b4060 fffff800`ab47e4fe : ffffe487`b18f1c90 ffffe487`b1267da0 ffffc480`00000000 fffff800`ab44d21f : nt!ExpWaitForResource+0x2a8
ffffc480`a28b4130 fffff800`ab90050b : 00000000`00000002 ffffc480`a28b41f0 ffffe487`b1827018 ffffc480`a28b42b0 : nt!ExAcquireResourceExclusiveLite+0x27e       
**ffffc480`a28b41b0 fffff800`ab48f72a : ffffc480`a28b44d0 ffffc480`a28b45c0 00000000`00000000 00000000`00000000 : nt!FsRtlAcquireFileForCcFlushEx+0x27f**
ffffc480`a28b4460 fffff800`ab476216 : 00000000`00000001 ffffe487`b4053800 00000000`00000000 00000000`00000000 : nt!MmFlushSection+0x9e
ffffc480`a28b4510 fffff800`ab497256 : ffffe487`b1827080 00000000`00000000 ffffe487`00000000 00000000`00000000 : nt!CcFlushCachePriv+0x616
ffffc480`a28b4620 fffff80e`0b54e39c : ffffe487`b1c8fc02 00000000`00000000 ffffe487`b1c8fc00 00000000`00000001 : nt!CcFlushCache+0x16                       
**ffffc480`a28b4660 fffff80e`0b541ad2 : ffffe487`b1827010 ffffe487`b12a32f0 ffffc480`a28b4759 ffffc480`a28b4890 : ThinFS!FlushFcb+0x13c            [f:\source\thincloud2.1\client\thinfs\sys\fileinfo.c @ 397]** 
ffffc480`a28b46a0 fffff80e`0b5483bc : ffffe487`b4f21760 ffffe487`b3c1d200 00000000`000003a0 000f0000`00000000 : ThinFS!DokanDispatchCleanup+0x2c2 [f:\source\thincloud2.1\client\thinfs\sys\cleanup.c @ 91] 
ffffc480`a28b4750 fffff80e`0b5480b0 : ffffe487`b4f21760 ffffe487`b3c1d200 00000000`00000000 ffffc480`a28b4890 : ThinFS!DokanDispatchRequest+0x2bc [f:\source\thincloud2.1\client\thinfs\sys\dispatch.c @ 147] 
ffffc480`a28b4790 fffff80e`09a05206 : ffffe487`b4f21760 ffffe487`b3c1d200 ffffe487`b3c1d200 ffffc480`a28b4890 : ThinFS!DokanBuildRequest+0x80 [f:\source\thincloud2.1\client\thinfs\sys\dispatch.c @ 45] 
ffffc480`a28b47e0 fffff80e`09a03146 : ffffffff`fffe7960 ffffe487`b4742060 00000000`00000001 ffffe487`b4742060 : FLTMGR!FltpLegacyProcessingAfterPreCallbacksCompleted+0x1a6
ffffc480`a28b4870 fffff800`ab823fb0 : ffffe487`b12a32f0 ffffe487`b4742060 00000000`00000000 fffff800`ab829cd4 : FLTMGR!FltpDispatch+0xb6
ffffc480`a28b48d0 fffff800`ab832315 : ffffe487`b12a32c0 00000000`00000000 ffffe487`b12a32c0 ffffe487`b12a32d0 : nt!IopCloseFile+0x150
ffffc480`a28b4960 fffff800`ab87c5db : 00000000`00000000 fffff800`ab8291c7 00000000`00000000 00000000`c000007b : nt!ObCloseHandleTableEntry+0x245
ffffc480`a28b4aa0 fffff800`ab568493 : ffffe487`b4053800 00000000`00000000 00000000`00000000 00000000`07ffbdd0 : nt!NtClose+0xcb
ffffc480`a28b4b00 00007ffe`47a962b4 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!KiSystemServiceCopyEnd+0x13 (TrapFrame @ ffffc480`a28b4b00)
00000000`0c11d3c8 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!NtClose+0x14

thread 2:

ffffc480`a0eaad20 fffff800`ab44846c : 00000000`00000000 00000000`00000001 ffffc480`a0eaafd0 fffff80e`00000001 : nt!KiSwapContext+0x76
ffffc480`a0eaae60 fffff800`ab447f0f : ffffe487`b0d33080 ffffe487`b0d33180 ffffe487`b34b6f80 00000000`00000000 : nt!KiSwapThread+0x17c
ffffc480`a0eaaf10 fffff800`ab44a1b8 : 00000000`00000000 ffffe487`b18270d0 00000000`000000fb ffffc480`a0eab0e0 : nt!KiCommitThreadWait+0x14f
ffffc480`a0eaafb0 fffff800`ab47ea95 : ffffe487`b18270d0 ffffc480`a0eab0c0 ffffe487`00000000 ffffe487`b0d33080 : nt!ExpWaitForResource+0x2a8
ffffc480`a0eab080 fffff800`ab9004dc : 00000000`00000002 ffffe487`b0c479f0 ffffe487`b1827018 ffffe487`b0c479f0 : nt!ExAcquireResourceSharedLite+0x365             
**ffffc480`a0eab110 fffff800`ab48f72a : ffffc480`a0eab430 ffffc480`a0eab4a0 00000000`00000000 00000000`00000000 : nt!FsRtlAcquireFileForCcFlushEx+0x250**
ffffc480`a0eab3c0 fffff800`ab49da74 : 00000000`00000000 ffffe487`b0d33080 00000000`00000000 00000000`00000000 : nt!MmFlushSection+0x9e
ffffc480`a0eab470 fffff800`ab84cfea : 00000000`00000000 00000000`00000002 ffffc480`a0eab5d8 00000000`00000000 : nt!MiFlushDataSection+0x84
ffffc480`a0eab4c0 fffff800`ab84863c : ffffe487`b1ce6080 00000000`00000000 ffffc480`a0eab769 00000000`00000000 : nt!MiCreateImageFileMap+0x122
ffffc480`a0eab670 fffff800`ab828455 : 00000000`00000002 00000000`01000000 ffffffff`ffffffff 00000000`00000080 : nt!MiCreateNewSection+0x1ec
ffffc480`a0eab7a0 fffff800`ab827afc : ffffc480`a0eaba60 00000000`00000000 00000000`00000000 ffffc480`a0eaba58 : nt!MiCreateSection+0x915
ffffc480`a0eab980 fffff800`ab828a55 : 00000000`00000000 ffffc480`a0eabb80 00000000`00003328 00000000`11000000 : nt!MmCreateSection+0xec
ffffc480`a0eaba10 fffff800`ab568493 : ffffe487`b0d33080 00000000`0736d5e8 ffffc480`a0eabaa8 00000000`07ffbdd0 : nt!NtCreateSection+0x175                           fcb resource 
ffffc480`a0eaba90 00007ffe`47a96a14 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!KiSystemServiceCopyEnd+0x13 (TrapFrame @ ffffc480`a0eabb00)
00000000`0736d5c8 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!NtCreateSection+0x14

I guess the cause of the deadlock is as follows:

          thread 1 
             |
          (FlushFcb)                                                   
          lock fcb->PagingIoResource[ LOCK A ]             |  thread 2
             |                                             |     | 
             |                                             |  (FsRtlAcquireFileForCcFlushEx)             
             |                                             |  lock fcb->AdvancedFCBHeader.Resource[ LOCK B ]
             |                                             |     |            
    (FsRtlAcquireFileForCcFlushEx)                         |  (FsRtlAcquireFileForCcFlushEx)                              
    will lock [ LOCK B ] , but can not lock , Because this |  will lock [ LOCK A ] , but can not lock , Because this lock 
    lock has been owned by thread 2                        |  has been owned by thread 1
    

i think calling CcFlushCache in our driver does not need to be lock(PagingIoResource) protected, 
We should apply for another lock to protect this call .

# Logs
Please attach in separate files: mirror output, library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan).
In case of BSOD, please attach minidump or dump analyze output.

### PR DESCRIPTION
**Pull request by fanlonglong8500**
fix #625

### CODE REVIEW

**Comment by Liryna** [comment]
Hi @fanlonglong8500 ,

Thank you for the PR!

I have not fully reviewed it but first look:
There is a broken test: https://ci.appveyor.com/project/Maxhy/dokany/build/1.1.0-342/job/8e8sixxlgakbf9yg#L410

Why disable DokanNotifyReportChange ?
https://github.com/dokan-dev/dokany/pull/632/files#diff-186f697a50e48562500c4beb285c7e58L365

**Comment by fanlonglong8500** [comment]
> Why disable DokanNotifyReportChange ?

I test ntfs . I found ntfs is reportchange on close.

> Acquire and release of resource here

See the following example 
[https://github.com/Microsoft/Windows-driver-samples/blob/aa6e0b36eb932099fa4eb950a6f5e289a23b6d6e/filesys/fastfat/cleanup.c#L991](url)

**Comment by fanlonglong8500** [comment]
你好 @Liryna ,
 A simple question, how do I get those test programs?

**Comment by Liryna** [comment]
You have the ifstest install script here: https://github.com/dokan-dev/dokany/tree/master/scripts
Winfstest: https://github.com/Liryna/winfstest

See how appveyor is using it: https://github.com/dokan-dev/dokany/blob/master/appveyor.yml
https://github.com/dokan-dev/dokany/blob/master/appveyor.yml#L260
https://github.com/dokan-dev/dokany/blob/master/samples/mirror_test.ps1

It is probably heavy to run everything like appveyor. Better to use first winfstest and after on another env the ifstest.

**Comment by fanlonglong8500** [comment]
Hi @Liryna ,
I've reviewed the code and found some problems, so you can wait for my next code submission before reviewing.

**Comment by fanlonglong8500** [comment]
Hi @Liryna ,
you can review now.

**Comment by Liryna** [comment]
Thank you @fanlonglong8500 !
I am currently busy. I will take a look this weekend hopefully !

**Comment by Liryna** [comment]
Hi @fanlonglong8500 ,

Sorry for the delay.

-Is there a reason for creating `COMPLETE_SUCCESS` instead of using `NTSTATUS` ? `SUCCESS/PENDING` 
-Bool isOk  should be renamed to `FCBAcquired`
-FILE_NOTIFY_CHANGE_SIZE is needed for IFTest `StreamNotifySizeTest` 😢 
https://github.com/Microsoft/Windows-driver-samples/blob/aa6e0b36eb932099fa4eb950a6f5e289a23b6d6e/filesys/fastfat/write.c#L2766

Otherwise, this seems to be a good work 👍 
Have you been able to reproduce https://github.com/dokan-dev/dokany/issues/625 without and see that it correctly fix it ?

Otherwise, I do not know if you have time or if you would like to do it but we have some IFSTest Oplock test that do not pass and we are looking for some help on it 👍

**Comment by fanlonglong8500** [comment]
> -Bool isOk should be renamed to FCBAcquired

The purpose of my design is to return PENGDING if some of the tasks in the complete function can not be completed immediately，including but not limited to FCB locker ( Although  there is only FCB Locker in this situation now )

In fact, this code modifies three issues：

1. #625.

2. NtCreateSection will  acquired FCB locker before send IRP ， when before this IRP have DokanOptions->ThreadCount IRP acquire this FCB locker will be deadlock.For example，there are DokanOptions->ThreadCount cleanup IRP before NtCreateSection IRP ， all of IRP are same file ，DeviceIoControl will be not return in SendEventInformation，because the cleanup IRPs will get the FCB lock, the FCB lock has been owned by  NtCreateSection IRP's thread. The NtCreateSection IRP does not have change to complte,beacase all work thread not return in DeviceIoControl . This commit greatly reduces the situation, but does not completely fix it. If you want to completely fix this problem, you need to modify many places.

3. fcb->AdvancedFCBHeader.Flags2 &= ~FSRTL_FLAG2_SUPPORTS_FILTER_CONTEXTS; If this flag not set ， the windows defender will not auto scan our file system. I observed NTFS file system, windows defender only scan the file once(right-click on an exe),But in dokan file system,windows defender auto scan the file every time(right-click on an exe),this will cause a particularly slow right-click on an exe.This change is not recommended incorporated into the mainstream version,because this change affects the filter file system behavior.


> Otherwise, this seems to be a good work 👍
> Have you been able to reproduce #625 without and see that it correctly fix it ?

In my environment,this commits correctly fix  #625.

> Otherwise, I do not know if you have time or if you would like to do it but we have some IFSTest Oplock test that do not pass and we are looking for some help on it 👍

Tks for inviting me,I may not be able to solve this problem, but I will try to solve it.How can I reproduce this problem?

**Comment by fanlonglong8500** [comment]
Hi @Liryna /ue415

**Comment by fanlonglong8500** [comment]
Hi @Liryna， :blush:

**Comment by Liryna** [comment]
Hi @fanlonglong8500 ,

Sorry year is starting with a lot of things in the same time 👍 


>3. fcb->AdvancedFCBHeader.Flags2 &= ~FSRTL_FLAG2_SUPPORTS_FILTER_CONTEXTS;

Wow I was not aware of that. Did you just see it or have you found something on Microsoft doc about it ?

Regarding the Oplock, the test not running is displayed on the CI, they are made by IFSTest
https://ci.appveyor.com/project/Maxhy/dokany/build/1.1.0-349/job/bioca6qhxkycxh9t#L957
You can run this test one by one with `/t OplockBreakItoIITest`
Oplock has a mechanism to make a request pending if it is not available. Maybe fixing this can improve the situation you described in 2) .
https://msdn.microsoft.com/en-us/library/gg607490(v=vs.85).aspx

I will do some test this weekend I promise 👍 !

**Comment by Liryna** [comment]
Hi @fanlonglong8500 ,

Made some test on my side and it seems to be stable 👍 Well done!
Nothing to say about the code else that my previous message. Maybe just some logs in case of allocation failure and when request cannot be queue.

Thank you

**Comment by fanlonglong8500** [comment]
> Wow I was not aware of that. Did you just see it or have you found something on Microsoft doc about it ?

When I discovered that the right-click exe was particularly slow due to windows defender, I disassembled fltmgr.sys and wdfilter.sys and I found this method can bypass the windows defender check.

I was recently analyzing the program trying to figure out why the right-click exe is particularly slow, but nothing has been done.

> Made some test on my side and it seems to be stable 👍 Well done!
Nothing to say about the code else that my previous message. Maybe just some logs in case of allocation failure and when request cannot be queue.

I will submit a revised commit according to your opinion, but FSRTL_FLAG2_SUPPORTS_FILTER_CONTEXTS do not want to change?

**Comment by Liryna** [comment]
`FSRTL_FLAG2_SUPPORTS_FILTER_CONTEXTS` would mean that we support context for each file streams.
It is probably benefic in the case you describe but I do not know what other features this requires or we already support it.

There is some informations here:
http://www.osronline.com/custom.cfm?name=articlePrint.cfm&id=356
https://msdn.microsoft.com/en-us/library/windows/hardware/ff547285(v=vs.85).aspx

**Comment by fanlonglong8500** [comment]
Hi @Liryna ,
Sorry , I am very busy recently，but i found the reason that caused a particularly slow right-click on an exe program.FCB  assicuates a context in wdfilter.sys , windows recoreds the results of the scan using context. when  FCB ref  down to 0, dokan release  FCB and also release the context.So windows scan the file every time. I guess the NTFS cache the FCB ,so the NTFS  does not have this situation.

**Comment by fanlonglong8500** [comment]
Hi @Liryna 
I modified the new code based on your suggestion,and I add FCB cache to resolve right-click problem.I guess FCB cache may pass some of the previously failed test. You help me to review the code of FCB cache ,especially in unmount and delete file.

**Comment by timofonic** [comment]
@fanlonglong8500 Thanks!

@Liryna Any news about this? Thanks in advance.

**Comment by Liryna** [comment]
Hi @fanlonglong8500 ,

Just to tell you I have reviewed at the code. it seems to be correct for me 👍 
I just need to review and test it more this weekend since it is sensitive part that is touched here.
Sorry for making you wait again.

What is LruFCB compared to cacheFCB ?
As I understood, you have created a fixed cache size that you cleanup it here https://github.com/dokan-dev/dokany/pull/632/files#diff-86caa6b16e4044982075fe5d5bc59915R205 How do you know what should be cleanup or not ?

**Comment by fanlonglong8500** [comment]
fcbcache contains a LRU list and a hash table.when a fcb FileCount down to 0,the qualified fcb will inserted into hash table and also insert into head of the LRU list.
there are three types of fcb that do not qualify:
1.fcb of stream
2.fcb of create file faild
3.fcb of deleted file

when fcbcache save the number of fcb more than MaxFcbCached,it will delete some recently not used fcb.LRU list help me to achieve these,because the fresh fcb always inserted into head of the LRU list.it is mean recently not used fcb will be at the end of LRU list.

typedef struct _FCB_CACHE_TABLE {
	PLIST_ENTRY Table;     //hash table
	LIST_ENTRY Lru;        //LRU list
	LONG TableSize;        //hash table slot number
        LONG MaxFcbCached;     //allow the maximum number of cached fcb
	LONG FcbCached;        //current number of cached fcb
}FCB_CACHE_TABLE, *PFCB_CACHE_TABLE;


BOOLEAN DokanInitFCBCache(__in PDokanVCB Vcb, __in LONG TableSize, __in LONG MaxCached) 
It is init fcbcache data structs
TableSize:init hash table slot number.if this value is 0, will use the default value(DOKAN_DEFAULT_CACHE_SIZE 509)
MaxCached:init maximum number of cached fcb.if this value is 0, will use the value of TableSize * 2

right-click an exe program:

before:
IRP_MJ_CREATE(In dokan, create new fcb and fcb FileCount is 1;In wdfilter.sys, found new fcb and scan it,store answer of scan into fcb's context)
IRP_MJ_CLOSE(In dokan, fcb's FileCount down to 0 and free it,FsRtlTeardownPerStreamContexts will callback wdfilter.sys free context) 
IRP_MJ_CREATE(In dokan, create new fcb and fcb FileCount is 1;In wdfilter.sys, found new fcb and scan it,store answer of scan into fcb's context)
IRP_MJ_CLOSE(In dokan, fcb's FileCount down to 0 and free it,FsRtlTeardownPerStreamContexts will callback wdfilter.sys free context) 
IRP_MJ_CREATE(In dokan, create new fcb and fcb FileCount is 1;In wdfilter.sys, found new fcb and scan it,store answer of scan into fcb's context)
IRP_MJ_CLOSE(In dokan, fcb's FileCount down to 0 and free it,FsRtlTeardownPerStreamContexts will callback wdfilter.sys free context) 
.....
.....
So the number of wdfilter scanning the same file is the same as the number of IRPs

now:
IRP_MJ_CREATE(In dokan, create new fcb and fcb FileCount is 1;In wdfilter.sys, found new fcb and scan it,store answer of scan into fcb's context)
IRP_MJ_CLOSE(In dokan, fcb's FileCount down to 0 and cache it,FsRtlTeardownPerStreamContexts will not be called) 
IRP_MJ_CREATE(In dokan, get old fcb from fcbcache;In wdfilter.sys, found old fcb and pass it)
IRP_MJ_CLOSE(In dokan, fcb's FileCount down to 0 and cache it,FsRtlTeardownPerStreamContexts will not be called)
IRP_MJ_CREATE(In dokan, get old fcb from fcbcache;In wdfilter.sys, found old fcb and pass it)
IRP_MJ_CLOSE(In dokan, fcb's FileCount down to 0 and cache it,FsRtlTeardownPerStreamContexts will not be called)
.....
.....
So the number of wdfilter scanning the same file is one.

As long as the value of MaxFcbCached can guarantee that fcb can be cached, during a right-click period,this problem will not appear.I tested default value can work well now.

**Comment by Liryna** [comment]
Hi @fanlonglong8500 ,

Thank you for the explanation and seems to be good for me and a good way to handle it 👍 
A little late for me now to review exactly all the code, so will need to wait more 😢 sorry for taking so long, busy days this time.

@marinkobabic if you can give a review and your input on this, it would be appreciated ❤️

**Comment by HanixNicolas** [comment]
@Liryna  Any news about this? 
@fanlonglong8500 Good fix.Thanks.

**Comment by HanixNicolas** [comment]
@fanlonglong8500 I test it on windows 10. It works fine in my ENV.Great fix.👍

**Comment by Liryna** [comment]
Hi @HanixNicolas ,

I agree this is a great fix 👍 I just could not find the time to review all the code and specially about the FCB / FCB Cache changes. Since it is in the driver part, I want to be sure that It cannot create crash / wrong behavior.
@HanixNicolas have you taken a look it ?

**Comment by HanixNicolas** [comment]
@Liryna I will spend some time to study the  code and discuss the fix with my friend who is good at Winows Driver.

**Comment by Liryna** [comment]
@HanixNicolas Oh that would be awesome thank you!

**Comment by fanlonglong8500** [comment]
@HanixNicolas If you don't understand my code, we can discuss together

**Comment by HanixNicolas** [comment]
@Liryna Hi,I have studied the code and disscus it with my friend.
what's more,do more test on both win7 and win10,it is ok.
Will you merge the code to the master ?
Do you have a plan to releas a new version?
@fanlonglong8500 Thank you.Good fix.👍 👍 👍

**Comment by HanixNicolas** [comment]
@Liryna  Hi, Any news about this?

**Comment by Liryna** [comment]
Hi @fanlonglong8500 ,

I am aware that this is taking too long (usually not the case 😢 ).
What is taking me time to review is the FCB Cache that I still wonder if it is a good solution to do and if that the right way to do.
Otherwise the pageio deadlock code is alright for me. Would you accept if I split your pull request (or you can do it) into two: pageio deadlock / FCB Cache ?
Like that I would merge the pageio deadlock and it would give me some time to look at more the FCB Cache ?

**Comment by fanlonglong8500** [comment]
@Liryna No problem, I understand your thoughts.

**Comment by Liryna** [comment]
Oplock and locks have been improved in 1.3.0
Thank you @fanlonglong8500 again for your work 👍

**Pull request closed without merging**
