### PR TITLE
Replaced the NSIS installer with WiX #116

### PR DESCRIPTION
**Pull request by Corillian**
Issue #116 
NOTE: Bootstrapper dependencies are currently not included, need to figure out how we want to handle these
NOTE: To properly install a certified WHQL driver a CatalogFile needs to be provided and Legacy="yes" needs to be set to "no" in the x64/x86 Product.wxs files
Added a new powershell based build script that properly reads the registry for Visual Studio's location
Version numbers need to be updated in each WiX installer, the bootstrapper, Dokan.BootstrapperUX, and finally dokan.inf. Find in Files is your best friend here.
Still a lot of testing required on various OS's and x86
Updated the solution to the latest Windows SDK

### CODE REVIEW

**Comment by Corillian** [comment]
Oops I tagged the wrong issue, it's #116

**Comment by Liryna** [comment]
Hi @Corillian ,

Thank you for the pull request !
I am having issue to build the installer:
```
1>------ Skipped Build: Project: DokanInstaller_x64, Configuration: Release x86 ------
1>Project not selected to build for this solution configuration 
2>------ Skipped Build: Project: DokanInstaller_x86, Configuration: Release x86 ------
2>Project not selected to build for this solution configuration 
3>------ Build started: Project: DokanInstaller_Bootstrapper, Configuration: Release x86 ------
3>	C:\Program Files (x86)\WiX Toolset v3.10\bin\candle.exe -d"DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\\" -dSolutionDir=C:\Users\liryna\Desktop\dokany\ -dSolutionExt=.sln -dSolutionFileName=dokan.sln -dSolutionName=dokan -dSolutionPath=C:\Users\liryna\Desktop\dokany\dokan.sln -dConfiguration=Release -dOutDir=bin\Release\ -dPlatform=x86 -dProjectDir=C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_Bootstrapper\ -dProjectExt=.wixproj -dProjectFileName=DokanInstaller_Bootstrapper.wixproj -dProjectName=DokanInstaller_Bootstrapper -dProjectPath=C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_Bootstrapper\DokanInstaller_Bootstrapper.wixproj -dTargetDir=C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_Bootstrapper\bin\Release\ -dTargetExt=.exe -dTargetFileName=DokanInstaller_Bootstrapper.exe -dTargetName=DokanInstaller_Bootstrapper -dTargetPath=C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_Bootstrapper\bin\Release\DokanInstaller_Bootstrapper.exe -dDokan.BootstrapperUX.Configuration=Release -d"Dokan.BootstrapperUX.FullConfiguration=Release|AnyCPU" -dDokan.BootstrapperUX.Platform=AnyCPU -dDokan.BootstrapperUX.ProjectDir=C:\Users\liryna\Desktop\dokany\dokan_install\Dokan.BootstrapperUX\ -dDokan.BootstrapperUX.ProjectExt=.csproj -dDokan.BootstrapperUX.ProjectFileName=Dokan.BootstrapperUX.csproj -dDokan.BootstrapperUX.ProjectName=Dokan.BootstrapperUX -dDokan.BootstrapperUX.ProjectPath=C:\Users\liryna\Desktop\dokany\dokan_install\Dokan.BootstrapperUX\Dokan.BootstrapperUX.csproj -dDokan.BootstrapperUX.TargetDir=C:\Users\liryna\Desktop\dokany\dokan_install\Dokan.BootstrapperUX\bin\Release\ -dDokan.BootstrapperUX.TargetExt=.dll -dDokan.BootstrapperUX.TargetFileName=Dokan.BootstrapperUX.dll -dDokan.BootstrapperUX.TargetName=Dokan.BootstrapperUX -dDokan.BootstrapperUX.TargetPath=C:\Users\liryna\Desktop\dokany\dokan_install\Dokan.BootstrapperUX\bin\Release\Dokan.BootstrapperUX.dll -dDokanInstaller_x64.Configuration=Release -d"DokanInstaller_x64.FullConfiguration=Release|x86" -dDokanInstaller_x64.Platform=x86 -dDokanInstaller_x64.ProjectDir=C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_x64\ -dDokanInstaller_x64.ProjectExt=.wixproj -dDokanInstaller_x64.ProjectFileName=DokanInstaller_x64.wixproj -dDokanInstaller_x64.ProjectName=DokanInstaller_x64 -dDokanInstaller_x64.ProjectPath=C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_x64\DokanInstaller_x64.wixproj -dDokanInstaller_x64.TargetDir=C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_x64\bin\Release\ -dDokanInstaller_x64.TargetExt=.msi -dDokanInstaller_x64.TargetFileName=DokanInstaller_x64.msi -dDokanInstaller_x64.TargetName=DokanInstaller_x64 -dDokanInstaller_x64.TargetPath=C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_x64\bin\Release\DokanInstaller_x64.msi -dDokanInstaller_x86.Configuration=Release -d"DokanInstaller_x86.FullConfiguration=Release|x86" -dDokanInstaller_x86.Platform=x86 -dDokanInstaller_x86.ProjectDir=C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_x86\ -dDokanInstaller_x86.ProjectExt=.wixproj -dDokanInstaller_x86.ProjectFileName=DokanInstaller_x86.wixproj -dDokanInstaller_x86.ProjectName=DokanInstaller_x86 -dDokanInstaller_x86.ProjectPath=C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_x86\DokanInstaller_x86.wixproj -dDokanInstaller_x86.TargetDir=C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_x86\bin\Release\ -dDokanInstaller_x86.TargetExt=.msi -dDokanInstaller_x86.TargetFileName=DokanInstaller_x86.msi -dDokanInstaller_x86.TargetName=DokanInstaller_x86 -dDokanInstaller_x86.TargetPath=C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_x86\bin\Release\DokanInstaller_x86.msi -out obj\Release\ -arch x86 -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixUtilExtension.dll" -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixBalExtension.dll" Bundle.wxs
3>	C:\Program Files (x86)\WiX Toolset v3.10\bin\Light.exe -out C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_Bootstrapper\bin\Release\DokanInstaller_Bootstrapper.exe -pdbout C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_Bootstrapper\bin\Release\DokanInstaller_Bootstrapper.wixpdb -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixUtilExtension.dll" -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixBalExtension.dll" -contentsfile obj\Release\DokanInstaller_Bootstrapper.wixproj.BindContentsFileList.txt -outputsfile obj\Release\DokanInstaller_Bootstrapper.wixproj.BindOutputsFileList.txt -builtoutputsfile obj\Release\DokanInstaller_Bootstrapper.wixproj.BindBuiltOutputsFileList.txt -wixprojectfile C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_Bootstrapper\DokanInstaller_Bootstrapper.wixproj obj\Release\Bundle.wixobj
3>C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_Bootstrapper\Bundle.wxs(54,0): error LGHT0103: The system cannot find the file 'C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_x64\bin\Release\DokanInstaller_x64.msi'.
3>C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_Bootstrapper\Bundle.wxs(55,0): error LGHT0103: The system cannot find the file 'C:\Users\liryna\Desktop\dokany\dokan_install\DokanInstaller_x86\bin\Release\DokanInstaller_x86.msi'.
3>Done building project "DokanInstaller_Bootstrapper.wixproj" -- FAILED.
3>
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 2 skipped ==========
```
For information, your installer need Framework 2.0 to be build. See http://wixtoolset.org/issues/3872/
Does this could be fixed ?

I really think the redist exe should not be part of the repository at all.
Adding 30mb at each VS version...it is unacceptable.

Otherwise, where did you got this version of the SDK ? (you have update WindowsTargetPlatformVersion of dokan_fuse and sys)
My VS have update 1 and impossible to find it.
https://github.com/dokan-dev/dokany/pull/125/files#diff-e8401a5bc872189984bafceb1cf636a5L77

**Comment by Corillian** [comment]
It's failing because it can't find the x86 and x64 MSI's because they aren't being built. The easiest way to build the bootstrapper is to run .\build.ps1 in powershell.

As for VS 2015 Update 1 you also need to update your your Windows SDK to the latest.

**Comment by js69** [comment]
Corillian, If you don't mind I would try to integrate your (driver install) stuff into mine.

I am note sure though if we really should use a custom bootstrapper like yours as it (unnecessarily) adds the requirement for .NET.

The use case for most Dokan deployments will have the .msi-files integrated into the App setup so practically nobody except devs will ever use the bootstrapper to install the drivers.

**Comment by Corillian** [comment]
You're free to integrate it into anything you'd like. While I would have preferred to avoid adding .NET as a dependency if you've ever attempted to create a robust UX using C/C++ then I think you'd agree that .NET is absolutely a necessary requirement. As you mention the people most likely to use the bootstrapper are developers and they're also the most likely to already have .NET installed. DokanInstaller_x64.msi and DokanInstaller_x86.msi can be distributed separately and they use the default WiX UI precisely for that reason.

**Comment by Liryna** [comment]
@js69 , @Corillian , I love both of your PR.
I have not been able to fully test them but as I first seen,
the UI of js69 seems to be more friendly and easy.
@Corillian seems to have been more deep in the driver installation feature as I understood.

Could you both mix your pull request to create one great installer ?

**Comment by js69** [comment]
I'll attempt to integrate everything with the standard Bootstrapper then.

**Comment by js69** [comment]
@Corillian The WiX projects won't open in Visual Studio 2015 SP1 (24720, Community) for me ("Unsupported"). Is that the case for you as well?

**Comment by Corillian** [comment]
I'm using Visual Studio 2015 Professional Update 1 and I don't have any problems. I haven't tried to open it in Community and I'm not entirely sure why that would be unsupported.

**Comment by Corillian** [comment]
Have you updated to the latest version of the Windows SDK?

**Comment by Liryna** [comment]
is it not because Express/Community does not support plugins ?

**Comment by Corillian** [comment]
My understanding is that Community isn't the same as Express and it does in fact support plugins.

**Comment by Corillian** [comment]
There's only 2 things I can think of that could be the problem. The first is sys.vcxproj:

```
- <WindowsTargetPlatformVersion>10.0.10240.0</WindowsTargetPlatformVersion>
+ <WindowsTargetPlatformVersion>10.0.10586.0</WindowsTargetPlatformVersion>
```

And the 2nd is dokan.sln:
```
- VisualStudioVersion = 14.0.23107.0
+ VisualStudioVersion = 14.0.24720.0
```

**Comment by Liryna** [comment]
Hi @Corillian ,

@js69 WiX Installer with your changes has been merged https://github.com/dokan-dev/dokany/commit/943a5d5c6551bc5085317c50d975bd8db55e73ac 

Thank you again for your help and your contribution it has been very helpful !

**Pull request closed without merging**
