### PR TITLE
#45 Change to NTSTATUS

### PR DESCRIPTION
**Pull request by Liryna**

### CODE REVIEW

**Comment by suy** [comment]
That was a quick merge. :-)

I suppose you know a lot better than me why this is needed and good, so I can't really oppose. I think this is also one of the things that DokanX changed, right? Good that both projects are more aligned, just in case.

Since I probably will need to port to the newer version, it will be good to have some minimum comments on porting. The changes in mirror.c are almost all needed. What surprises me, is that more or less you moved from the library to the user applications the win32 to NTSTATUS switch-case that maps one to other. I don't understand what is gained by that. :open_mouth: 

The switch-case in create.c was in the wiki of my project because I wanted to know which status code I can return from CreateFile, so the user has a moderately useful error message. I suppose there isn't much that you can do, right? The OS will give generic error messages?

Thank you!

**Comment by marinkobabic** [comment]
You have a much better control what status should be returned to the os. So you can decide what message should be displayed to the user. Depending on NTSTATUS the os behaves different in specific cases. Now it's up to you to decide what happened in your code and how you want report it to the is respective to user. 
Before the change you had the code -1 which means nothing for os. 

NTSTATUS provides more direct reporting to os and user. It gives you more flexibility.

**Comment by suy** [comment]
Oh, then that's excellent news! I reviewed the differences, but not understanding everything properly I thought there was still some checking of specific return values that were the ones supported. Thank you!

**Comment by Liryna** [comment]
This commit was in branch since some weeks now, I had one issue that I have only  been able to correct yesterday.

you can find some information to convert your Win32 error here:
https://support.microsoft.com/en-us/kb/113996

or here, but you should be very careful because like @marinkobabic told, there is specific case where you cannot answer what you want.
So this switch case **should only be used as example of error conversion**.
https://www.eldos.com/forum/read.php?PAGEN_1=4&TID=688

```
    NTSTATUS
    Error2NtStatus(
        IN ULONG Win32ErrorCode              
        )
    {
        switch(Win32ErrorCode)
        {
        case ERROR_SUCCESS:
            return STATUS_SUCCESS;
     
        case ERROR_ACCESS_DENIED:
            return STATUS_ACCESS_DENIED;
            
        case ERROR_NOACCESS:
            return STATUS_ACCESS_VIOLATION;
     
        case ERROR_NOT_SUPPORTED:
            return STATUS_NOT_SUPPORTED;
     
        case ERROR_INVALID_PARAMETER:
            return STATUS_INVALID_PARAMETER;
     
        case ERROR_INVALID_HANDLE:
            return STATUS_INVALID_HANDLE;
     
        case ERROR_NOT_LOCKED:
            return STATUS_NOT_LOCKED;
     
        case ERROR_NO_SYSTEM_RESOURCES:
            return STATUS_INSUFFICIENT_RESOURCES;
     
        case ERROR_NOT_ENOUGH_MEMORY:
            return STATUS_NO_MEMORY;                        
     
        case ERROR_MORE_DATA:
            return STATUS_BUFFER_OVERFLOW;
     
        case ERROR_INSUFFICIENT_BUFFER:
            return STATUS_BUFFER_TOO_SMALL;
            
        case ERROR_NO_MORE_FILES:
            return STATUS_NO_MORE_FILES;
     
        case ERROR_FILE_NOT_FOUND:    
            return STATUS_NO_SUCH_FILE;
     
        case ERROR_INVALID_FUNCTION:
            return STATUS_NOT_SUPPORTED;
     
        case ERROR_CALL_NOT_IMPLEMENTED:
            return STATUS_NOT_IMPLEMENTED;
     
        case ERROR_HANDLE_EOF:
            return STATUS_END_OF_FILE;
     
        case ERROR_INVALID_NAME:
            return STATUS_OBJECT_NAME_INVALID;
     
        case ERROR_DISK_FULL:
            return STATUS_DISK_FULL;
     
        case ERROR_DISK_CORRUPT:
            return STATUS_DISK_CORRUPT_ERROR;
     
        case ERROR_BAD_COMMAND:
            return STATUS_INVALID_DEVICE_STATE;
     
        case ERROR_FILE_EXISTS:
            return STATUS_OBJECT_NAME_COLLISION;
     
        case ERROR_ALREADY_EXISTS:
            return STATUS_OBJECT_NAME_COLLISION;
     
        case ERROR_CANNOT_MAKE:
            return STATUS_CANNOT_MAKE;
     
        case ERROR_PROC_NOT_FOUND:
            return STATUS_PROCEDURE_NOT_FOUND;
     
        case ERROR_OPERATION_ABORTED:
            return STATUS_CANCELLED;
     
        case ERROR_IO_DEVICE:
        case TYPE_E_IOERROR:
            return STATUS_IO_DEVICE_ERROR;
     
        case ERROR_BAD_UNIT:
            return STATUS_NO_SUCH_DEVICE; //STATUS_DEVICE_DOES_NOT_EXIST
     
        case ERROR_BAD_ARGUMENTS:
            return STATUS_INVALID_PARAMETER;
     
        case ERROR_BAD_EXE_FORMAT:
            return STATUS_INVALID_IMAGE_FORMAT;
     
        case ERROR_WAIT_NO_CHILDREN:
            return STATUS_NOT_FOUND;
     
        case ERROR_RETRY:
            return STATUS_RETRY;
     
        case ERROR_INVALID_ADDRESS:
            return STATUS_CONFLICTING_ADDRESSES;
     
        case ERROR_BUSY:
            return STATUS_DEVICE_BUSY;
     
        case ERROR_DIRECTORY:
            return STATUS_NOT_A_DIRECTORY;
     
        case ERROR_TOO_MANY_OPEN_FILES:
            return STATUS_TOO_MANY_OPENED_FILES;
     
        case ERROR_EA_TABLE_FULL:
            return STATUS_EA_TOO_LARGE;
     
        case ERROR_FILE_INVALID:
            return STATUS_FILE_INVALID;
     
        case ERROR_CONNECTION_UNAVAIL:
            return STATUS_CONNECTION_DISCONNECTED; //STATUS_DFS_UNAVAILABLE                  
     
        case ERROR_TOO_MANY_LINKS:
            return STATUS_TOO_MANY_LINKS;
     
        case ERROR_BROKEN_PIPE:
            return STATUS_PIPE_BROKEN;
     
        case ERROR_ARITHMETIC_OVERFLOW:
            return STATUS_INTEGER_OVERFLOW;
     
        case ERROR_POSSIBLE_DEADLOCK:
            return STATUS_POSSIBLE_DEADLOCK;
     
        case ERROR_BUFFER_OVERFLOW:
            return STATUS_NAME_TOO_LONG;
     
        case ERROR_TOO_MANY_SEMAPHORES:
            return STATUS_INSUFFICIENT_RESOURCES;
     
        case ERROR_DIR_NOT_EMPTY:
            return STATUS_DIRECTORY_NOT_EMPTY;
     
        case ERROR_PATH_NOT_FOUND:
            return STATUS_OBJECT_PATH_NOT_FOUND;
     
        case ERROR_ARENA_TRASHED:
            return STATUS_DISK_CORRUPT_ERROR;
     
        case ERROR_INVALID_BLOCK:
            return STATUS_INVALID_ADDRESS;
     
        case ERROR_BAD_ENVIRONMENT:
            return STATUS_VARIABLE_NOT_FOUND;
     
        case ERROR_SHARING_VIOLATION:
            return STATUS_SHARING_VIOLATION;
     
        case ERROR_FILENAME_EXCED_RANGE:
            return STATUS_NAME_TOO_LONG;
     
        case ERROR_NOT_READY:
            return STATUS_DEVICE_NOT_READY; //or STATUS_NO_MEDIA_IN_DEVICE, STATUS_VOLUME_DISMOUNTED
     
        case ERROR_FILE_OFFLINE:
            return STATUS_FILE_IS_OFFLINE;    
     
        case ERROR_REMOTE_STORAGE_NOT_ACTIVE:
            return STATUS_REMOTE_STORAGE_NOT_ACTIVE;
     
        //
        // Winsock errors
        //
     
        case WSAEINTR:
            return STATUS_CANCELLED;
     
        case WSAEBADF:
            return STATUS_INVALID_HANDLE;
     
        case WSATRY_AGAIN:
            return STATUS_RETRY;
     
        default:
            return STATUS_UNSUCCESSFUL;
        }
    }
```

**Comment by rustyx** [comment]
So, now I'm supposed to map Win32 GetLastError() first to NTSTATUS using somehow, then have that mapped to errno, pass it to dokan_fuse, which would translate errno back to NTSTATUS? Does not sound like an improvement to me.

Nice code sample, but there are >2000 NTSTATUSes en Win32 errors.

**Comment by Liryna** [comment]
@rustyx Without using NTSTATUS error, dokan would not be able to answer correctly to the kernel windows. Before dokan was answering the same dummy ntstatus error when user was returning a GetLastError(). Now the mirror sample is much more stable and answer correctly to all request.

If you was using `win32_error_to_errno` (replaced by ntstatus_error_to_errno) you was anyway already using a switch/case -> https://github.com/dokan-dev/dokany/blob/15343707589097d1b6941946506a5b9dac5d4eda/dokan_fuse/src/utils.cpp#L265-L312

**Comment by Liryna** [comment]
Helper DokanNtStatusFromWin32 has been added in Dokan Library and can be used to translate Win32 Error code to the NtStatus code's corresponding

**Pull request merged**
