### PR TITLE
Fix cert manager

### LINKED ISSUE #589: \cert\dokan-import.ps1 script should warn if SecureBoot is enabled (PowerShell)
`\cert\dokan-import.ps1` ([documentation here](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot)) is a PowerShell-script used for installing a self-signed certificate that is used for development builds and configures Windows to run testsigned drivers. This does not work on newer Windows versions when SecureBoot is enabled.

The script should not proceed or output a warning if SecureBoot is enabled to avoid confused users that want to test a bugfix.

### PR DESCRIPTION
**Pull request by Absoblogginlutely**
Fixes #589  .

### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the existing documentation
- [x] My changes generate no new warnings
- [x] I have updated the change log (Add/Change/Fix)
- [ ] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

-Updated dokan-import.ps1 to check if running as admin and relaunch if not. Also wraps existing function in a check for secureboot being enabled.

First Pull request so hope I did this right.

### CODE REVIEW

**Comment by Liryna** [comment]
Hi @Absoblogginlutely ,

Thank a lot for the contribution !
I was not aware `Confirm-SecureBootUEFI` existed ! That's good to know !

Could you just fix the indentation of the powershell script ?
(For the changelog, I will update in a second the versions, you will probably need to merge it)

**Comment by Absoblogginlutely** [comment]
Updated Indentation - I think thats how you would want it. Let me know if not. I think the PR should also go back to pending?

**Comment by Rondom** [comment]
This is about asking the user to DISABLE SecureBoot if it is enabled..

You cannot use drivers with a self-signed certificate when SecureBoot is enabled. The purpose of the script is to import a self-signed certificate and enabling running drivers signed by self-signed certificates. This is used when running a driver that you build yourself for development purposes. Using that driver signed with a self-signed certificate will fail if SecureBoot is enabled. This is why we want to add a check that SecureBoot is disabled.

**Comment by Liryna** [comment]
Thank you @Rondom you made a good point here 👍 . My bad I did not look enough.

**Comment by Absoblogginlutely** [comment]
Thanks @Rondom Rondom for the clarification. @Liryna I think it should be good now.

**Comment by Liryna** [comment]
Hi @Absoblogginlutely ,

Thanks a lot for the quick changes ! Everything seems to be right. @Rondom also for you ?
In the mean time, @Absoblogginlutely could you rebase the commits into one (probably there is going to be a merge conflict with the readme)

**Comment by Rondom** [comment]
Ok from my side. Commit should be squashed into one commit.

**Comment by Absoblogginlutely** [comment]
I think this is done correctly - this was tougher than I thought but a great learning experience for a first PR.

**Comment by Liryna** [comment]
Hi @Absoblogginlutely ,

Thanks a lot again for your contribution it is very appreciated and glad to see it was a great experience for your first PR ! Hope it will not be the last 😃 for the opensource !

**Pull request merged**
