### PR TITLE
check for GDR/LDR version of KB3033929 in bundle

### PR DESCRIPTION
**Pull request by zanderz**
@Rondom suggests this check may be helpful in the bundle, not just the individual packages.

### CODE REVIEW

**Comment by Liryna** [comment]
Hi @zanderz ,

Thank you for your contribution ! :+1: 

Is it not the same as https://github.com/dokan-dev/dokany/commit/9782a6491775ef3660a71f40f381d3f48e511f14 ?

**Comment by Rondom** [comment]
No. Without this, the bundle will happily install all kinds of stuff like .NET only to then fail while installing the MSI at the end. If I remember my tests correctly at least .NET installation is not even rolled back. With this patch, we fail early.

**Comment by Liryna** [comment]
Alright @Rondom ! I agree that it would give a better experience to add this check before.

Does the check should not be 
((WINTRUSTVERSION >= v6.1.7601.18741 AND WINTRUSTVERSION `<` v6.1.7601.22000) OR WINTRUSTVERSION >= v6.1.7601.229`48`)) ?

**Comment by Rondom** [comment]
Depends on whether the bundle-engine follows arcane MSI implementation details that make one pull their hair out :-D

**Comment by js69** [comment]
There is a minor text bug: " ... the installation of Keybase."

**Comment by Rondom** [comment]
I would guess you do not need to decrease the version number by one, because here the version number is stored in a variable and I would expect at least basic operators like greater, lesser and equal would work in a sane way. Then again you don't know whether the right number gets stored I the variable... Googling made me none the wiser. In the worst case I will have to test with both the GDR and LDR patch...

**Comment by Rondom** [comment]
http://wixtoolset.org/documentation/manual/v3/xsd/util/filesearch.html
^ this suggests that the bundle behaviour is sane i.e. no decrementing needed

**Comment by zanderz** [comment]
Whoops, sorry about the product name, I fixed that.
Our reason for moving this logic out of the package and into the bundle is for our own bundle to show coherent errors to the user. At first, our bundle included the Dokan bundle in its chain, and when run silently, all its errors were masked, and worst of all, the visual studio redistributable package could cause an unprompted reboot. Now we have copied all the same prerequisites from the Dokan bundle to ours, and just chained the .msi packages.

Speaking of which: it would be very helpful if the .msi packages were included in the release binaries, so we hopefully someday can stop building + signing our own.

**Comment by Liryna** [comment]
@Rondom I agree with you, just that Wintrust.dll has version 6.1.7601.18741 and 6.1.7601.22948
https://support.microsoft.com/en-us/kb/3033929
So the check should be `WINTRUSTVERSION >= v6.1.7601.22948` and since LDR start as 22xxx the check should be `WINTRUSTVERSION < v6.1.7601.22000`.

@zanderz :+1: for the msi packages ! I added it to the build script (it remind me to upload it :smiley: ) https://github.com/dokan-dev/dokany/commit/8885fefe75e1aaa299cf94ef19a70428c396cafb

**Comment by Liryna** [comment]
@zanderz I am ready to merge your PR, I am just waiting for the changes on the version value as describe before (correct me if I am not wrong in my way I think this work :smile: ) and also rebase into a single commit.

**Comment by zanderz** [comment]
Changed to `WINTRUSTVERSION < v6.1.7601.22000` and squashed down.

**Comment by zanderz** [comment]
I changed it, but note that it doesn't match the packages, because MinVersion is inclusive.

**Comment by Liryna** [comment]
>I changed it, but note that it doesn't match the packages, because MinVersion is inclusive.

Here it is directly the correct version of the wintrust that we compare, there is no MinVersion.

I tested it on Win7 with and without GDR/LDR KB and got the correct message just before dependency get installed :+1: 

Good job @zanderz and very appreciate !

**Pull request merged**
